// 100 poster categories. Each row: key, name, group, emoji, kicker, title, subtitle, details (| separated), call to action, palette, default size
const ROWS = [
  // Festivals
  ['diwali', 'Diwali', 'Festivals', '🪔', 'Wishing you a', 'Happy Diwali', 'May the festival of lights brighten your home with joy and prosperity', 'From: Your Name & Family', '', 'festive', 'insta-post'],
  ['holi', 'Holi', 'Festivals', '🎨', 'Celebrate the colours', 'Happy Holi', 'Let the colours of joy, love and happiness fill your life', 'Holi Milan: 14 March, 10 AM|Community Park, Sector 21', 'Join the celebration', 'holi', 'insta-post'],
  ['eid', 'Eid Mubarak', 'Festivals', '🌙', 'Warm wishes', 'Eid Mubarak', 'May Allah bless you with peace, happiness and prosperity', 'From: Your Name & Family', '', 'night', 'insta-post'],
  ['christmas', 'Christmas', 'Festivals', '🎄', 'Season’s greetings', 'Merry Christmas', 'Wishing you a season full of light and laughter', 'Christmas Eve Party · 24 Dec, 7 PM', '', 'xmas', 'insta-post'],
  ['new-year', 'New Year', 'Festivals', '🎆', 'Cheers to', 'Happy New Year 2027', 'New beginnings, new dreams, new successes', 'Countdown Party · 31 Dec, 9 PM onwards', 'Book your pass', 'night', 'insta-post'],
  ['ganesh-chaturthi', 'Ganesh Chaturthi', 'Festivals', '🐘', 'Ganpati Bappa Morya', 'Happy Ganesh Chaturthi', 'May Lord Ganesha remove all obstacles from your life', 'Sthapana: 7 Sept, 11 AM|Visarjan: 17 Sept', '', 'saffron', 'insta-post'],
  ['navratri', 'Navratri & Garba', 'Festivals', '💃', 'Nine nights of devotion', 'Navratri Garba Night', 'Dandiya · Garba · Live music · Prizes for best dressed', '3–11 October · 8 PM onwards|City Club Grounds', 'Passes: ₹299', 'holi', 'poster-a4'],
  ['durga-puja', 'Durga Puja', 'Festivals', '🔱', 'Shubho', 'Durga Puja', 'May Maa Durga bless you with strength and happiness', 'Pandal: Sector 15 Community Hall|Bhog daily at 1 PM', '', 'festive', 'insta-post'],
  ['dussehra', 'Dussehra', 'Festivals', '🏹', 'Victory of good over evil', 'Happy Dussehra', 'May this Vijayadashami bring you success in everything you do', 'Ravan Dahan · 12 Oct, 6 PM|Ramlila Maidan', '', 'saffron', 'insta-post'],
  ['raksha-bandhan', 'Raksha Bandhan', 'Festivals', '🧶', 'A bond of love', 'Happy Raksha Bandhan', 'To the sweetest bond between brothers and sisters', '', '', 'rose', 'insta-post'],
  ['janmashtami', 'Janmashtami', 'Festivals', '🦚', 'Jai Shri Krishna', 'Happy Janmashtami', 'May Lord Krishna fill your life with love and joy', 'Dahi Handi · 16 Aug, 4 PM', '', 'peacock', 'insta-post'],
  ['ram-navami', 'Ram Navami', 'Festivals', '🏹', 'Jai Shri Ram', 'Happy Ram Navami', 'May the blessings of Lord Ram be with you always', 'Shobha Yatra · 10 AM from Ram Mandir', '', 'saffron', 'insta-post'],
  ['maha-shivratri', 'Maha Shivratri', 'Festivals', '🔱', 'Har Har Mahadev', 'Maha Shivratri', 'May Lord Shiva bless you with health, peace and prosperity', 'Rudrabhishek · 4 AM onwards', '', 'night', 'insta-post'],
  ['makar-sankranti', 'Makar Sankranti / Lohri', 'Festivals', '🪁', 'Fly high', 'Happy Makar Sankranti', 'Til gud ghya, god god bola', 'Kite festival · 14 Jan, 10 AM', '', 'sky', 'insta-post'],
  ['pongal-onam', 'Pongal & Onam', 'Festivals', '🌾', 'Harvest wishes', 'Happy Pongal', 'May this harvest festival bring abundance to your home', '', '', 'earth', 'insta-post'],
  ['chhath', 'Chhath Puja', 'Festivals', '🌅', 'Jai Chhathi Maiya', 'Happy Chhath Puja', 'May the Sun God bless you with health and happiness', 'Ghat: River Front, Sector 9', '', 'sunset', 'insta-post'],
  ['bhai-dooj', 'Bhai Dooj', 'Festivals', '🪔', 'A bond forever', 'Happy Bhai Dooj', 'Celebrating the love between brothers and sisters', '', '', 'rose', 'insta-post'],
  ['dhanteras', 'Dhanteras', 'Festivals', '🪙', 'Shubh', 'Dhanteras', 'May Goddess Lakshmi bless you with wealth and prosperity', 'Gold & silver offers up to 25% off', 'Visit our store', 'festive', 'insta-post'],
  ['gurpurab', 'Guru Nanak Jayanti', 'Festivals', '🙏', 'Waheguru Ji Ka Khalsa', 'Happy Gurpurab', 'May the teachings of Guru Nanak Dev Ji guide your path', 'Langar from 11 AM', '', 'saffron', 'insta-post'],
  ['karva-chauth', 'Karva Chauth', 'Festivals', '🌕', 'Love that lasts', 'Happy Karva Chauth', 'Wishing you a lifetime of love and togetherness', 'Mehendi & Puja Thali offers', '', 'rose', 'insta-post'],
  // National days
  ['independence-day', 'Independence Day', 'National days', '🇮🇳', '15 August', 'Happy Independence Day', 'Saluting the spirit of freedom and the heroes who made it possible', 'Flag hoisting · 8 AM|Cultural programme to follow', '', 'tricolour', 'insta-post'],
  ['republic-day', 'Republic Day', 'National days', '🇮🇳', '26 January', 'Happy Republic Day', 'Proud to be Indian. Celebrating our Constitution', 'Flag hoisting · 8 AM', '', 'tricolour', 'insta-post'],
  ['gandhi-jayanti', 'Gandhi Jayanti', 'National days', '🕊️', '2 October', 'Gandhi Jayanti', '“Be the change you wish to see in the world.”', '', '', 'mono', 'insta-post'],
  ['yoga-day', 'Yoga Day', 'National days', '🧘', '21 June', 'International Yoga Day', 'Free yoga session for everyone. Bring your own mat', '6:00–7:30 AM|Central Park, Gate 2', 'Register free', 'mint', 'poster-a4'],
  ['womens-day', 'Women’s Day', 'National days', '👩', '8 March', 'Happy Women’s Day', 'Celebrating the strength, grace and courage of every woman', '', '', 'purple', 'insta-post'],
  ['teachers-day', 'Teachers’ Day', 'National days', '📚', '5 September', 'Happy Teachers’ Day', 'Thank you for inspiring us to learn, dream and grow', '', '', 'royal', 'insta-post'],
  ['childrens-day', 'Children’s Day', 'National days', '🧒', '14 November', 'Happy Children’s Day', 'Every child is a different kind of flower', 'Fun fair · Games · Prizes', '', 'sky', 'insta-post'],
  ['environment-day', 'Environment Day', 'National days', '🌳', '5 June', 'World Environment Day', 'Plant a tree, save the planet', 'Tree plantation drive · 7 AM', 'Join us', 'green', 'poster-a4'],
  ['mothers-day', 'Mother’s Day', 'National days', '💐', 'To the best mom', 'Happy Mother’s Day', 'Thank you for your endless love and care', '', '', 'rose', 'insta-post'],
  ['fathers-day', 'Father’s Day', 'National days', '👔', 'To my hero', 'Happy Father’s Day', 'Thank you for always being there for me', '', '', 'ocean', 'insta-post'],
  // Wishes
  ['welcome', 'Welcome', 'Wishes & greetings', '🙏', 'A very warm', 'Welcome', 'We are delighted to have you with us', 'Your Name · Your Organisation', '', 'royal', 'poster-a4'],
  ['congratulations', 'Congratulations', 'Wishes & greetings', '🎉', 'Heartiest', 'Congratulations!', 'On your outstanding achievement. We are proud of you', 'Rahul Sharma|Selected for IIT Delhi', '', 'festive', 'insta-post'],
  ['birthday', 'Birthday', 'Wishes & greetings', '🎂', 'Wishing you a very', 'Happy Birthday', 'May all your dreams come true. Have a wonderful year ahead', 'Priya', '', 'pink', 'insta-post'],
  ['anniversary', 'Anniversary', 'Wishes & greetings', '💞', 'Happy', 'Anniversary', 'To a couple who makes love look beautiful', 'Amit & Neha · 10 Years', '', 'rose', 'insta-post'],
  ['thank-you', 'Thank you', 'Wishes & greetings', '💐', 'From the bottom of our hearts', 'Thank You', 'For your support, trust and love', 'Your Name', '', 'mint', 'insta-post'],
  ['good-morning', 'Good morning', 'Wishes & greetings', '☀️', 'Have a beautiful day', 'Good Morning', 'Every morning is a new beginning. Smile and start again', '', '', 'sunset', 'insta-post'],
  ['good-night', 'Good night', 'Wishes & greetings', '🌙', 'Sweet dreams', 'Good Night', 'Rest well and wake up to a brighter tomorrow', '', '', 'night', 'insta-post'],
  ['get-well-soon', 'Get well soon', 'Wishes & greetings', '🌻', 'Sending healing wishes', 'Get Well Soon', 'Wishing you a speedy recovery and good health', '', '', 'sky', 'insta-post'],
  ['condolence', 'Shraddhanjali / Condolence', 'Wishes & greetings', '🕯️', 'In loving memory', 'Shraddhanjali', 'Late Shri Ram Prasad Ji|1945 – 2026', 'Prarthana Sabha: Sunday, 4 PM|Community Hall', '', 'mono', 'poster-a4'],
  ['retirement', 'Retirement', 'Wishes & greetings', '🎖️', 'Happy', 'Retirement', 'Thank you for 35 years of dedicated service', 'Mr. S. K. Verma', '', 'royal', 'insta-post'],
  ['farewell', 'Farewell', 'Wishes & greetings', '👋', 'We will miss you', 'Farewell Party', 'Class of 2026', 'Friday, 3 PM · School Auditorium', '', 'purple', 'poster-a4'],
  ['motivational-quote', 'Motivational quote', 'Wishes & greetings', '💡', 'Quote of the day', '“Dream big. Start small. Act now.”', '— Your Name', '', '', 'mono', 'insta-post'],
  // Events & invitations
  ['wedding', 'Wedding invitation', 'Events & invitations', '💍', 'Together with their families', 'Rohan weds Ananya', 'Request the pleasure of your company', 'Saturday, 12 December 2026 · 7 PM|The Grand Palace, Jaipur', 'RSVP: +91 98765 43210', 'festive', 'invitation'],
  ['engagement', 'Engagement', 'Events & invitations', '💍', 'Save the date', 'Engagement Ceremony', 'Karan & Simran', 'Sunday, 8 November · 6 PM|Hotel Royal Orchid', '', 'rose', 'invitation'],
  ['housewarming', 'Housewarming / Griha Pravesh', 'Events & invitations', '🏡', 'You are invited to our', 'Griha Pravesh', 'Bless our new home with your presence', 'Sunday, 15 March · 10 AM|Flat 402, Green Valley Apartments', 'Lunch to follow', 'saffron', 'invitation'],
  ['baby-shower', 'Baby shower', 'Events & invitations', '🍼', 'Oh baby!', 'Baby Shower', 'Join us to celebrate the little one on the way', 'Saturday, 4 PM|Our home', '', 'pink', 'invitation'],
  ['naming-ceremony', 'Naming ceremony', 'Events & invitations', '👶', 'Namkaran Sanskar', 'Naming Ceremony', 'Bless our little angel with your presence', 'Sunday, 11 AM|Shree Hall', '', 'sky', 'invitation'],
  ['birthday-party', 'Birthday party invite', 'Events & invitations', '🎈', 'You’re invited!', 'Aarav turns 5', 'Games · Cake · Magic show', 'Sunday, 20 Dec · 5 PM|Fun Zone, City Mall', 'RSVP: +91 98765 43210', 'sky', 'invitation'],
  ['jagran', 'Jagran / Kirtan', 'Events & invitations', '🛕', 'Jai Mata Di', 'Maa Bhagwati Jagran', 'All devotees are invited', 'Saturday night, 9 PM onwards|Shiv Mandir Park', 'Bhandara after Jagran', 'saffron', 'poster-a4'],
  ['bhandara', 'Bhandara', 'Events & invitations', '🍛', 'Sabhi bhakton ko amantran', 'Vishal Bhandara', 'Prasad for everyone', 'Tuesday, 12 PM onwards|Hanuman Mandir', '', 'saffron', 'poster-a4'],
  ['katha', 'Katha / Satsang', 'Events & invitations', '📿', 'Shrimad Bhagwat', 'Katha Saptah', 'Kathavachak: Pt. Ramesh Shastri Ji', '1–7 November · 2 PM to 6 PM|Ram Leela Ground', '', 'festive', 'poster-a4'],
  ['concert', 'Concert / Music night', 'Events & invitations', '🎤', 'Live in concert', 'Music Night', 'An evening of soulful Bollywood and Sufi music', 'Saturday, 8 PM|City Auditorium', 'Tickets from ₹499', 'night', 'poster-a4'],
  ['dj-party', 'DJ party', 'Events & invitations', '🎧', 'This Saturday', 'DJ Night', 'Dance till you drop with DJ Rocky', '9 PM onwards · Club Zero', 'Entry: ₹999 couple', 'neon', 'story'],
  ['workshop', 'Workshop / Seminar', 'Events & invitations', '🧑‍🏫', 'Free workshop', 'Digital Marketing Masterclass', 'Learn SEO, ads and social media from experts', 'Sunday, 11 AM–2 PM|Tech Hub, 3rd Floor', 'Register now', 'royal', 'poster-a4'],
  ['webinar', 'Webinar', 'Events & invitations', '💻', 'Live webinar', 'How to Crack Interviews', 'With HR experts from top companies', 'Saturday · 7 PM on Zoom', 'Register free', 'ocean', 'fb-post'],
  ['sports-tournament', 'Sports tournament', 'Events & invitations', '🏏', 'Season 5', 'Cricket Premier League', '16 teams · Big prizes · Trophy & cash', 'Starts 10 January|Sports Complex', 'Entry fee ₹2,100 per team', 'green', 'poster-a4'],
  ['marathon', 'Marathon / Run', 'Events & invitations', '🏃', 'Run for health', 'City Marathon 2026', '5K · 10K · 21K', 'Sunday, 6 AM|Start: Stadium Gate 1', 'Register now', 'coral', 'poster-a4'],
  ['exhibition', 'Exhibition / Fair', 'Events & invitations', '🎪', 'Mega', 'Trade Fair & Exhibition', '200+ stalls · Food court · Kids zone', '10–15 December · 11 AM–9 PM|Exhibition Ground', 'Free entry', 'purple', 'poster-a4'],
  // Business & offers
  ['sale', 'Sale / Discount', 'Business & offers', '🛍️', 'Mega', 'SALE', 'Flat 50% off on everything', 'This weekend only|All stores & online', 'Shop now', 'sale', 'insta-post'],
  ['festival-offer', 'Festival offer', 'Business & offers', '🎁', 'Festive', 'Big Festive Offer', 'Up to 70% off + extra 10% on prepaid orders', 'Valid till 31 October', 'Shop now', 'festive', 'insta-post'],
  ['grand-opening', 'Grand opening', 'Business & offers', '🎀', 'Grand', 'Opening', 'Your Store Name', 'Sunday, 10 AM|Shop 12, Main Market', 'Special opening offers', 'festive', 'poster-a4'],
  ['coming-soon', 'Coming soon', 'Business & offers', '⏳', 'Something big is', 'Coming Soon', 'Stay tuned for the launch', '@yourbrand', '', 'night', 'insta-post'],
  ['product-launch', 'Product launch', 'Business & offers', '🚀', 'Introducing', 'The New Product X', 'Faster. Smarter. Better.', 'Available from 1 November', 'Pre-order now', 'ocean', 'insta-post'],
  ['business-promotion', 'Business promotion', 'Business & offers', '📈', 'Grow with us', 'Your Business Name', 'Quality products · Best prices · Fast delivery', '+91 98765 43210|www.yourbusiness.com', 'Call now', 'royal', 'insta-post'],
  ['restaurant', 'Restaurant / Cafe', 'Business & offers', '🍕', 'Taste the best', 'Pizza Party', 'Buy 1 Get 1 free on all large pizzas', 'Every Tuesday|Free home delivery', 'Order: 98765 43210', 'coral', 'insta-post'],
  ['bakery', 'Bakery / Cake shop', 'Business & offers', '🧁', 'Freshly baked', 'Cakes & Pastries', 'Custom cakes for birthdays and anniversaries', 'Order 24 hours in advance', 'Call 98765 43210', 'pink', 'insta-post'],
  ['menu', 'Food menu', 'Business & offers', '📜', 'Today’s', 'Menu', 'Paneer Butter Masala ₹220|Dal Makhani ₹180|Veg Biryani ₹200|Butter Naan ₹40', 'Free delivery above ₹500', '', 'earth', 'poster-a4'],
  ['fashion', 'Fashion / Boutique', 'Business & offers', '👗', 'New arrivals', 'Festive Collection', 'Sarees · Lehengas · Kurtis', 'Flat 30% off this week', 'Visit store', 'rose', 'insta-portrait'],
  ['jewellery', 'Jewellery', 'Business & offers', '💎', 'Shine bright', 'Jewellery Collection', 'Gold · Diamond · Silver', '0% making charges on gold', 'Visit showroom', 'festive', 'insta-portrait'],
  ['mobile-shop', 'Mobile / Electronics', 'Business & offers', '📱', 'Best deals', 'Mobiles & Accessories', 'EMI from ₹999 · Exchange offers', 'All brands available', 'Visit today', 'ocean', 'insta-post'],
  ['furniture', 'Furniture', 'Business & offers', '🛋️', 'Make your home beautiful', 'Furniture Sale', 'Sofas · Beds · Dining sets', 'Up to 40% off', 'Free delivery', 'earth', 'insta-post'],
  ['car-bike', 'Car / Bike sale', 'Business & offers', '🚗', 'Drive home today', 'Car Mela', 'New & used cars · Easy finance', 'Saturday–Sunday|Auto Hub, NH-48', 'Book a test drive', 'sale', 'poster-a4'],
  ['salon', 'Salon / Beauty parlour', 'Business & offers', '💇', 'Look your best', 'Beauty Salon', 'Haircut · Facial · Bridal makeup', '20% off on first visit', 'Book: 98765 43210', 'pink', 'insta-post'],
  ['gym', 'Gym / Fitness', 'Business & offers', '🏋️', 'No pain, no gain', 'Join Our Gym', 'Personal training · Cardio · Zumba', 'Admission open · 50% off', 'Call 98765 43210', 'neon', 'insta-post'],
  ['travel', 'Travel / Tour package', 'Business & offers', '✈️', 'Explore', 'Goa Tour Package', '3 nights · 4 days · Hotel + sightseeing', 'Starting at ₹9,999 per person', 'Book now', 'sky', 'insta-post'],
  ['visiting-card', 'Visiting card', 'Business & offers', '📇', 'Proprietor', 'Your Name', 'Your Business Name', '+91 98765 43210|you@business.com|Shop 12, Main Market', '', 'royal', 'business-card'],
  ['price-list', 'Price list / Rate card', 'Business & offers', '🏷️', 'Our', 'Price List', 'Haircut ₹150|Shave ₹80|Hair colour ₹500|Facial ₹600', '', '', 'mono', 'poster-a4'],
  // Real estate
  ['property-sale', 'Property for sale', 'Real estate', '🏠', 'For sale', 'Luxury 3 BHK Flats', 'Ready to move · Modular kitchen · Covered parking', 'Starting ₹65 lakh|Sector 45, Gurugram', 'Call 98765 43210', 'royal', 'poster-a4'],
  ['rent', 'House for rent', 'Real estate', '🔑', 'To-let', 'House for Rent', '2 BHK · Semi furnished · Near metro', '₹18,000 per month', 'Call 98765 43210', 'green', 'poster-a4'],
  ['plots', 'Plots / Land', 'Real estate', '🗺️', 'Book now', 'Residential Plots', 'Gated colony · Wide roads · Clear title', 'Easy EMI · Bank loan available', 'Site visit: 98765 43210', 'earth', 'poster-a4'],
  ['housing-project', 'Housing project', 'Real estate', '🏢', 'New launch', 'Green Valley Homes', '2 & 3 BHK apartments with clubhouse and pool', 'Possession 2028', 'Book your home', 'ocean', 'flex-banner'],
  ['commercial-space', 'Shop / Office space', 'Real estate', '🏬', 'Commercial', 'Shops & Offices', 'Prime location · High footfall', 'Lease or buy', 'Call now', 'mono', 'poster-a4'],
  // Politics & social
  ['election', 'Election poster', 'Politics & social', '🗳️', 'Vote for', 'Your Candidate Name', 'Ward No. 12 · Municipal Election 2026', 'Vikas · Vishwas · Imaandari|Voting on 5 November', 'Press the button against our symbol', 'saffron', 'poster-a4'],
  ['vote-appeal', 'Vote appeal', 'Politics & social', '☝️', 'Your vote, your voice', 'Go Vote', 'Every vote counts. Vote on 5 November', '', '', 'saffron', 'insta-post'],
  ['political-party', 'Party / Leader greeting', 'Politics & social', '🙏', 'Heartfelt greetings from', 'Your Leader Name', 'Ward Councillor, Ward No. 12', 'Seva hi sankalp', '', 'saffron', 'insta-post'],
  ['blood-donation', 'Blood donation camp', 'Politics & social', '🩸', 'Donate blood, save lives', 'Blood Donation Camp', 'Every drop counts', 'Sunday, 9 AM–3 PM|Community Hall', 'Register: 98765 43210', 'red', 'poster-a4'],
  ['health-camp', 'Free health camp', 'Politics & social', '🩺', 'Free', 'Health Check-up Camp', 'BP · Sugar · Eye test · Dental', 'Sunday, 10 AM–4 PM|Govt. School', 'All are welcome', 'mint', 'poster-a4'],
  ['awareness', 'Awareness campaign', 'Politics & social', '♻️', 'Clean city, green city', 'Swachh Bharat', 'Keep your surroundings clean', 'Say no to plastic', '', 'green', 'poster-a4'],
  ['missing', 'Missing / Lost & found', 'Politics & social', '🔍', 'Please help', 'Missing', 'Name: Rohit, Age 12|Last seen near City Bus Stand', 'Contact: 98765 43210', 'Reward offered', 'red', 'poster-a4'],
  ['notice', 'Notice / Announcement', 'Politics & social', '📢', 'Important', 'Notice', 'The society meeting will be held on Sunday at 11 AM in the clubhouse. All members are requested to attend.', 'Secretary, RWA', '', 'mono', 'poster-a4'],
  ['holiday-notice', 'Holiday / Closed notice', 'Politics & social', '🚫', 'Notice', 'Shop Closed', 'Closed on Sunday for Diwali', 'We will reopen on Monday', '', 'red', 'poster-a4'],
  // Education
  ['admission-open', 'Admission open', 'Education', '🎓', 'Session 2026–27', 'Admissions Open', 'Nursery to Class 12 · CBSE affiliated', 'Smart classes · Transport · Sports', 'Call 98765 43210', 'royal', 'poster-a4'],
  ['coaching', 'Coaching / Tuition', 'Education', '📖', 'Join today', 'Coaching Classes', 'Maths · Science · English for Class 6–12', 'New batch from 1 April', 'Free demo class', 'ocean', 'poster-a4'],
  ['result', 'Toppers / Result', 'Education', '🏆', 'Proud of our', 'Toppers 2026', 'Ananya 98.6% · Rohan 97.2% · Meera 96.8%', '100% result', 'Admissions open', 'festive', 'insta-post'],
  ['certificate', 'Certificate', 'Education', '📜', 'Certificate of', 'Achievement', 'This is proudly presented to', 'Your Name|For outstanding performance', '', 'certificate', 'certificate'],
  ['school-event', 'School annual day', 'Education', '🎭', 'You are invited to our', 'Annual Day', 'Celebrating talent and achievement', 'Friday, 5 PM|School Auditorium', '', 'purple', 'poster-a4'],
  // Jobs
  ['hiring', 'We are hiring', 'Jobs', '🧑‍💼', 'Join our team', 'We Are Hiring', 'Sales Executive · Accountant · Receptionist', 'Freshers welcome|Salary ₹15,000–30,000', 'Send CV: jobs@company.com', 'royal', 'insta-post'],
  ['walk-in', 'Walk-in interview', 'Jobs', '🚶', 'Walk-in', 'Interview', 'For customer support (voice process)', 'Monday–Friday, 10 AM–4 PM|Tower B, Cyber City', 'Bring your resume', 'ocean', 'poster-a4'],
  ['freelancer', 'Freelancer / Services', 'Jobs', '🧑‍💻', 'Available for work', 'Website Design', 'Websites · Logos · Social media posts', 'Starting at ₹4,999', 'WhatsApp 98765 43210', 'neon', 'insta-post'],
  // Health & services
  ['clinic', 'Doctor / Clinic', 'Health & services', '🏥', 'Your health, our priority', 'Dr. Sharma’s Clinic', 'General physician · Diabetes · BP', 'Mon–Sat: 10 AM–2 PM, 5–8 PM', 'Call 98765 43210', 'mint', 'poster-a4'],
  ['pharmacy', 'Pharmacy', 'Health & services', '💊', 'Open 24×7', 'City Medical Store', 'All medicines · Free home delivery', '10% off on every order', 'Call 98765 43210', 'green', 'insta-post'],
  ['insurance', 'Insurance / Finance', 'Health & services', '🛡️', 'Secure your family', 'Life Insurance', 'Plans starting at ₹499 per month', 'Tax benefits under 80C', 'Talk to an advisor', 'ocean', 'insta-post'],
  ['loan', 'Loan / EMI', 'Health & services', '💰', 'Quick approval', 'Personal Loan', 'Up to ₹10 lakh at low interest', 'Minimal documents · 24-hour disbursal', 'Apply now', 'royal', 'insta-post'],
  ['pest-control', 'Home services', 'Health & services', '🧰', 'Trusted experts', 'Home Services', 'Plumbing · Electrician · AC repair · Pest control', 'Same-day service', 'Call 98765 43210', 'sky', 'insta-post'],
  ['youtube', 'YouTube thumbnail', 'Social media', '▶️', 'New video', 'You Won’t Believe This!', 'Watch till the end', '', '', 'neon', 'yt-thumb'],
];

export const POSTER_CATEGORIES = ROWS.map(([key, name, group, emoji, kicker, title, sub, details, cta, palette, format]) => ({
  key, name, group, emoji, kicker, title, sub, details: details ? details.split('|') : [], cta, palette, format,
}));

export const POSTER_GROUPS = [...new Set(POSTER_CATEGORIES.map((c) => c.group))];

export const getPosterCategory = (key) => POSTER_CATEGORIES.find((c) => c.key === key);
