// Generated templates: every category gets one template per visual style (20 styles), built from that
// category's content pack. Hand-made templates in templates.js count toward a category's 20.
import { DEFAULT_THEME, img, makeBlock as b } from './blocks';

const theme = (t) => ({ ...DEFAULT_THEME, ...t });
const pal = (primary, secondary, bg, surface, text, muted, border) => ({ primary, secondary, bg, surface, text, muted, border });

// ---------- 20 visual styles ----------
// hero: split | image-left | center | cover | feature (3D hero for tech, centered elsewhere)
// order: which section sequence to use (ORDERS below) · band: alternate section backgrounds · dev: use the interactive developer blocks
export const STYLES = [
  { slug: 'aurora', name: 'Aurora', premium: true, desc: 'Dark glow, gradient light and bold type.', hero: 'feature', heroImage: false, order: 0, skills: 'tags', cols: 3, gallery: 'masonry', dev: true, mode: true,
    theme: { ...pal('#7C5CFF', '#22D3EE', '#0B0D14', '#131722', '#E8EAF2', '#9097AD', '#262B3B'), headingFont: 'Space Grotesk', bodyFont: 'Inter', letterSpacing: -0.03, radius: 14, buttonStyle: 'pill', pattern: 'gradient', baseSize: 16,
      altPrimary: '#5B3DF5', altBg: '#FFFFFF', altSurface: '#F5F6FB', altText: '#151826', altMuted: '#5D6378', altBorder: '#E3E5EF' } },
  { slug: 'slate', name: 'Slate', premium: false, desc: 'Clean, confident and easy to read.', hero: 'split', order: 1, skills: 'bars', cols: 2, gallery: 'grid', band: true,
    theme: { ...pal('#2F5BFF', '#FFB020', '#FFFFFF', '#F5F7FB', '#16213E', '#5B6680', '#E1E6EF'), headingFont: 'Manrope', bodyFont: 'Inter', headingWeight: '800', radius: 12 } },
  { slug: 'paper', name: 'Paper', premium: false, desc: 'Warm cream pages with editorial serif type.', hero: 'image-left', order: 2, skills: 'tags', cols: 2, gallery: 'wide', narrow: true,
    theme: { ...pal('#B4462B', '#E9C46A', '#FBF7F0', '#FFFFFF', '#2A2420', '#6E625A', '#E8DFD3'), headingFont: 'Fraunces', bodyFont: 'Inter', headingWeight: '600', letterSpacing: -0.01, radius: 4, buttonStyle: 'square' } },
  { slug: 'midnight', name: 'Midnight', premium: false, desc: 'Code-editor darkness with a monospace edge.', hero: 'center', heroImage: false, order: 0, skills: 'tags', cols: 3, gallery: 'grid', dev: true, mode: true,
    theme: { ...pal('#3FB950', '#58A6FF', '#0D1117', '#161B22', '#E6EDF3', '#8B949E', '#30363D'), headingFont: 'JetBrains Mono', bodyFont: 'IBM Plex Sans', letterSpacing: -0.01, radius: 8, pattern: 'grid', baseSize: 16,
      altPrimary: '#1F883D', altBg: '#FFFFFF', altSurface: '#F6F8FA', altText: '#1F2328', altMuted: '#59636E', altBorder: '#D1D9E0' } },
  { slug: 'coral', name: 'Coral', premium: false, desc: 'Bright coral accents and big rounded shapes.', hero: 'split', order: 3, skills: 'circles', cols: 3, gallery: 'masonry',
    theme: { ...pal('#FF4D2E', '#1E1E24', '#F7F7FB', '#FFFFFF', '#1E1E24', '#6B6B78', '#E3E3EC'), headingFont: 'Syne', bodyFont: 'DM Sans', headingWeight: '800', letterSpacing: -0.03, radius: 18, buttonStyle: 'pill' } },
  { slug: 'forest', name: 'Forest', premium: false, desc: 'Calm greens and a soft serif headline.', hero: 'image-left', order: 1, skills: 'bars', cols: 2, gallery: 'grid', band: true,
    theme: { ...pal('#1F6F50', '#E9C46A', '#F4F8F5', '#FFFFFF', '#14251D', '#56685E', '#D7E3DB'), headingFont: 'DM Serif Display', bodyFont: 'Figtree', headingWeight: '400', letterSpacing: 0, radius: 10 } },
  { slug: 'noir', name: 'Noir', premium: true, desc: 'Full-bleed cover, black canvas, poster type.', hero: 'cover', order: 2, skills: 'tags', cols: 2, gallery: 'grid',
    theme: { ...pal('#F5F5F5', '#E63946', '#0A0A0A', '#151515', '#F5F5F5', '#A1A1A1', '#262626'), headingFont: 'Bebas Neue', bodyFont: 'Work Sans', headingWeight: '400', letterSpacing: 0.02, radius: 0, buttonStyle: 'square', maxWidth: 1240 } },
  { slug: 'lilac', name: 'Lilac', premium: false, desc: 'Friendly pastel colour and soft dots.', hero: 'split', order: 3, skills: 'circles', cols: 3, gallery: 'grid',
    theme: { ...pal('#7C4DFF', '#FF8FB1', '#FBF8FF', '#FFFFFF', '#2A2340', '#6E6788', '#E9E1F7'), headingFont: 'Fredoka', bodyFont: 'Nunito', headingWeight: '600', letterSpacing: -0.01, radius: 24, buttonStyle: 'pill', pattern: 'dots' } },
  { slug: 'ivory', name: 'Ivory', premium: true, desc: 'Quiet luxury: ivory, gold and fine serif.', hero: 'center', order: 1, skills: 'tags', cols: 2, gallery: 'wide', narrow: true,
    theme: { ...pal('#8A6A3B', '#C9A96E', '#FAF8F3', '#FFFFFF', '#1F1B16', '#6F675C', '#E6E0D4'), headingFont: 'Cormorant Garamond', bodyFont: 'Jost', headingWeight: '600', letterSpacing: 0, radius: 2, buttonStyle: 'square', baseSize: 18 } },
  { slug: 'ocean', name: 'Ocean', premium: false, desc: 'Fresh blues with a sunny accent.', hero: 'split', order: 0, skills: 'bars', cols: 3, gallery: 'masonry',
    theme: { ...pal('#0EA5E9', '#F97316', '#F0F9FF', '#FFFFFF', '#0C2A3E', '#4B6476', '#D5E7F2'), headingFont: 'Outfit', bodyFont: 'Inter', radius: 16, pattern: 'gradient' } },
  { slug: 'sunset', name: 'Sunset', premium: false, desc: 'Warm gradients and chunky display type.', hero: 'center', heroImage: false, order: 2, skills: 'tags', cols: 3, gallery: 'grid',
    theme: { ...pal('#F43F5E', '#FB923C', '#FFF7F2', '#FFFFFF', '#2B1A1F', '#74595F', '#F2DCD3'), headingFont: 'Unbounded', bodyFont: 'Figtree', headingWeight: '700', letterSpacing: -0.02, radius: 20, buttonStyle: 'pill', pattern: 'gradient' } },
  { slug: 'graphite', name: 'Graphite', premium: false, desc: 'Minimal black-and-white, nothing extra.', hero: 'center', heroImage: false, order: 1, skills: 'bars', cols: 2, gallery: 'grid', narrow: true,
    theme: { ...pal('#111827', '#10B981', '#FFFFFF', '#F3F4F6', '#111827', '#6B7280', '#E5E7EB'), headingFont: 'Inter', bodyFont: 'Inter', headingWeight: '700', letterSpacing: -0.03, radius: 6, maxWidth: 980 } },
  { slug: 'neon', name: 'Neon', premium: true, desc: 'Glowing cyan and pink on deep navy.', hero: 'feature', heroImage: false, order: 3, skills: 'tags', cols: 3, gallery: 'masonry', dev: true,
    theme: { ...pal('#00E5FF', '#FF2E97', '#0A0A1A', '#12122A', '#F1F1FF', '#9A9AC0', '#26264A'), headingFont: 'Space Grotesk', bodyFont: 'Outfit', letterSpacing: -0.03, radius: 14, buttonStyle: 'pill', pattern: 'gradient' } },
  { slug: 'sand', name: 'Sand', premium: false, desc: 'Earthy tones and a friendly book serif.', hero: 'image-left', order: 0, skills: 'bars', cols: 2, gallery: 'wide', band: true,
    theme: { ...pal('#9C6644', '#DDB892', '#F6F1EA', '#FFFFFF', '#2F2621', '#75675C', '#E6DACB'), headingFont: 'Lora', bodyFont: 'Source Sans 3', headingWeight: '600', letterSpacing: -0.01, radius: 8 } },
  { slug: 'royal', name: 'Royal', premium: true, desc: 'Navy and gold, classic and trustworthy.', hero: 'split', order: 2, skills: 'bars', cols: 3, gallery: 'grid', band: true,
    theme: { ...pal('#1E3A8A', '#D4AF37', '#FFFFFF', '#F5F7FC', '#0F172A', '#5B6478', '#E2E8F0'), headingFont: 'Playfair Display', bodyFont: 'Lato', headingWeight: '700', letterSpacing: -0.01, radius: 4, buttonStyle: 'square' } },
  { slug: 'mint', name: 'Mint', premium: false, desc: 'Crisp mint green with playful dots.', hero: 'split', order: 3, skills: 'circles', cols: 3, gallery: 'masonry',
    theme: { ...pal('#059669', '#FBBF24', '#F0FDF7', '#FFFFFF', '#0B2E22', '#4D6B5F', '#CDEBDD'), headingFont: 'Poppins', bodyFont: 'Poppins', headingWeight: '700', letterSpacing: -0.02, radius: 14, pattern: 'dots' } },
  { slug: 'brutal', name: 'Brutal', premium: false, desc: 'Neo-brutalist: hard edges, loud yellow.', hero: 'center', heroImage: false, order: 0, skills: 'tags', cols: 2, gallery: 'grid',
    theme: { ...pal('#111111', '#FFD23F', '#FFE8D6', '#FFFFFF', '#111111', '#5A4A3F', '#111111'), headingFont: 'Archivo Black', bodyFont: 'Work Sans', headingWeight: '400', letterSpacing: 0, radius: 0, buttonStyle: 'square',
      customCSS: '.pf-card,.pf-btn,.pf-input{box-shadow:4px 4px 0 #111}.pf-card{border-width:2px}' } },
  { slug: 'cherry', name: 'Cherry', premium: true, desc: 'Rich berry tones with fashion-magazine type.', hero: 'image-left', order: 1, skills: 'tags', cols: 3, gallery: 'masonry',
    theme: { ...pal('#9D174D', '#F9A8D4', '#FFF5F8', '#FFFFFF', '#3B0A1F', '#7D5566', '#F5D5E0'), headingFont: 'Abril Fatface', bodyFont: 'Raleway', headingWeight: '400', letterSpacing: 0, radius: 12, buttonStyle: 'pill' } },
  { slug: 'steel', name: 'Steel', premium: false, desc: 'Corporate blue, structured and sharp.', hero: 'split', order: 2, skills: 'bars', cols: 3, gallery: 'grid', band: true,
    theme: { ...pal('#0B5394', '#C7A008', '#FFFFFF', '#F4F7FA', '#1A2330', '#5A6878', '#DDE4EC'), headingFont: 'Montserrat', bodyFont: 'Source Sans 3', headingWeight: '700', letterSpacing: -0.02, radius: 4, buttonStyle: 'square', baseSize: 18 } },
  { slug: 'carbon', name: 'Carbon', premium: true, desc: 'Charcoal with electric lime highlights.', hero: 'cover', order: 3, skills: 'tags', cols: 3, gallery: 'masonry', dev: true, mode: true,
    theme: { ...pal('#A3E635', '#22D3EE', '#101010', '#1A1A1A', '#F2F2F2', '#A3A3A3', '#2B2B2B'), headingFont: 'Bricolage Grotesque', bodyFont: 'Inter', headingWeight: '800', letterSpacing: -0.03, radius: 12, pattern: 'grid',
      altPrimary: '#4D7C0F', altBg: '#FFFFFF', altSurface: '#F5F5F4', altText: '#141414', altMuted: '#57534E', altBorder: '#E7E5E4' } },
];

const ORDERS = [
  ['stats', 'about', 'skills', 'work', 'exp', 'testimonials', 'services', 'extra', 'cta', 'contact'],
  ['about', 'work', 'services', 'skills', 'stats', 'exp', 'testimonials', 'extra', 'contact'],
  ['work', 'about', 'exp', 'skills', 'testimonials', 'stats', 'extra', 'cta', 'contact'],
  ['services', 'about', 'stats', 'work', 'skills', 'extra', 'testimonials', 'exp', 'contact'],
];

export const NAMES = [
  'Aarav Mehta', 'Diya Kapoor', 'Kabir Rao', 'Ananya Iyer', 'Vihaan Shah', 'Ishita Verma', 'Arjun Nair', 'Meera Joshi', 'Rohan Das', 'Saanvi Gupta',
  'Aditya Kulkarni', 'Tara Menon', 'Yash Malhotra', 'Nisha Reddy', 'Karan Bose', 'Priya Sethi', 'Dev Chawla', 'Zoya Khan', 'Neel Banerjee', 'Riya Pillai',
];

const QUOTES = {
  tech: [['Shipped faster than any contractor we have used, and the code was clean.', 'Head of Engineering, Northwind'], ['Calm under pressure and great at explaining trade-offs.', 'CTO, Brightloop']],
  visual: [['Our brand finally looks like the company we are.', 'Founder, Kettle & Co'], ['Fast, thoughtful and full of ideas we would never have had.', 'Marketing Lead, Bloom']],
  business: [['Clear thinking, clear numbers, clear results.', 'CEO, Meridian'], ['The most reliable partner we brought on this year.', 'COO, Atlas Retail']],
  people: [['Patient, kind and genuinely brilliant at what they do.', 'Happy client'], ['I recommend them to every friend and family member.', 'Long-time client']],
};

// ---------- content packs, one per category ----------
// k: kind (tech | visual | business | people | linkbio) · s: skills · sv: services · pr: projects · ex: experience · st: stats
// work: 'gallery' | 'projects' · extra: kind-specific extra section · stack: tech stack groups
export const PACKS = {
  Minimal: { k: 'people', role: 'Writer & consultant', title: 'Simple ideas, carefully explained.', sub: 'I help teams say what they mean, in fewer words.', about: 'I have spent ten years writing for products, publications and the occasional cereal box. I like plain language, short sentences and long walks.', s: 'Writing, Editing, Strategy, Research, Workshops', sv: [['Writing', 'Articles, guides and web copy.'], ['Editing', 'Make long things short and clear.'], ['Workshops', 'Teach your team to write better.']], pr: [['Field notes', 'A weekly newsletter for 12,000 readers.', 'Writing'], ['Clear docs', 'Rewrote a SaaS help centre.', 'Docs'], ['Small book', 'A guide to calm work.', 'Book']], ex: [['Independent', 'Self-employed', '2020 – now', 'Writing and editing for product teams.'], ['Senior Editor', 'Pagewise', '2015 – 2020', 'Led a team of six editors.']], st: [['10', 'Years writing'], ['80+', 'Clients'], ['12k', 'Newsletter readers']], work: 'projects', extra: 'faq' },
  Creative: { k: 'visual', role: 'Creative director', title: 'Loud ideas, carefully made.', sub: 'Brand identities, campaigns and art direction for brands that want to be remembered.', about: 'I lead small creative teams from first sketch to final launch. Ten years across studios in Mumbai and London.', s: 'Art direction, Branding, Illustration, Campaigns, Motion', sv: [['Brand identity', 'Logos, colour and type that last.'], ['Campaigns', 'Ideas that travel across channels.'], ['Art direction', 'Shoots and visuals with a point of view.']], pr: [['Kettle & Co', 'Rebrand for a tea startup.', 'Branding'], ['Monsoon', 'Campaign for a fashion label.', 'Campaign'], ['Paper Moon', 'Illustrated packaging.', 'Packaging']], ex: [['Creative Director', 'Studio Nine', '2021 – now', 'Leading brand and campaign work.'], ['Senior Designer', 'Pentagram (contract)', '2017 – 2021', 'Identity projects for global clients.']], st: [['10', 'Years in design'], ['120', 'Brands shaped'], ['14', 'Awards']], work: 'gallery', extra: 'logos' },
  Developer: { k: 'tech', role: 'Software developer', title: 'I build fast, reliable web apps.', sub: 'Full-stack JavaScript, clean APIs and boring, dependable infrastructure.', about: 'I have been writing code for eight years, mostly for startups. I care about readable code, good tests and shipping on time.', s: 'TypeScript, React, Node.js, PostgreSQL, Docker, AWS', stack: [['Frontend', 'React, Next.js, TypeScript, Tailwind CSS'], ['Backend', 'Node.js, Express, GraphQL'], ['Data & Ops', 'PostgreSQL, Redis, Docker, AWS']], sv: [['Web apps', 'From idea to production.'], ['APIs', 'Fast, documented, tested.'], ['Code review', 'Make your codebase healthier.']], pr: [['queue-kit', 'Tiny Redis job queue, 1.1k stars.', 'Node.js, Redis'], ['ledgerly', 'Open-source bookkeeping API.', 'TypeScript, PostgreSQL'], ['tiny-cron', 'Cron scheduling for serverless.', 'AWS, Go']], ex: [['Senior Developer', 'Paylite', '2022 – now', 'Payments platform, 2M requests a day.'], ['Developer', 'Brightloop', '2018 – 2022', 'Built the customer dashboard.']], st: [['8', 'Years coding'], ['1.2k', 'GitHub stars'], ['40+', 'Projects shipped']] },
  Photography: { k: 'visual', role: 'Photographer', title: 'Light, people and places worth remembering.', sub: 'Weddings, portraits and travel. Based in Jaipur, shooting everywhere.', about: 'I photograph real moments with as little fuss as possible. Twelve years, four continents, one favourite lens.', s: 'Weddings, Portraits, Travel, Editing, Lighting', sv: [['Weddings', 'Full-day coverage and albums.'], ['Portraits', 'Studio or outdoor sessions.'], ['Travel', 'Brand and tourism shoots.']], pr: [['Udaipur wedding', 'Three days by the lake.', 'Wedding'], ['Ladakh in winter', 'A personal travel series.', 'Travel'], ['Old Delhi mornings', 'Street portraits.', 'Street']], ex: [['Lead Photographer', 'Self-employed', '2016 – now', '200+ weddings across India.'], ['Assistant', 'Studio Frame', '2013 – 2016', 'Lighting and post-production.']], st: [['12', 'Years shooting'], ['200+', 'Weddings'], ['30', 'Countries']], work: 'gallery', extra: 'pricing' },
  Business: { k: 'business', role: 'Business consultant', title: 'Turning messy operations into growth.', sub: 'I help founders fix the process, the numbers and the team behind them.', about: 'Fifteen years in operations and strategy, from a 10-person startup to a listed retailer. I like problems with spreadsheets attached.', s: 'Strategy, Operations, Finance, Leadership, Negotiation', sv: [['Strategy', 'Where to play and how to win.'], ['Operations', 'Processes that scale.'], ['Fundraising', 'Decks and models investors trust.']], pr: [['Retail turnaround', 'Back to profit in 14 months.', 'Operations'], ['Series A', 'Raised ₹40Cr for a D2C brand.', 'Fundraising'], ['Market entry', 'Launched in the UAE.', 'Strategy']], ex: [['Principal', 'Meridian Advisory', '2019 – now', 'Strategy for growth-stage companies.'], ['Head of Ops', 'Atlas Retail', '2012 – 2019', '140 stores, 1,400 people.']], st: [['15', 'Years experience'], ['₹900Cr', 'Revenue influenced'], ['40', 'Companies helped']], work: 'projects', extra: 'logos' },
  'Link in bio': { k: 'linkbio', role: 'Creator', title: '@yourname', sub: 'Recipes, travel and everyday notes. New video every Friday.', links: [['Latest video', 'New'], ['My recipe e-book', '₹299'], ['Brand collaborations', ''], ['Join the newsletter', 'Free']] },

  IT: { k: 'tech', role: 'IT professional', title: 'Keeping systems running so people can work.', sub: 'Infrastructure, support and security for growing companies.', about: 'I manage networks, devices and cloud tools for teams of 20 to 500. Fewer outages, faster help desks, happier staff.', s: 'Windows Server, Linux, Networking, Microsoft 365, Azure, ITIL', stack: [['Systems', 'Linux, Windows Server, Bash'], ['Cloud', 'Azure, AWS, Microsoft 365'], ['Network', 'Cisco, Firewalls, VPN']], sv: [['IT support', 'Fast, friendly help desk.'], ['Infrastructure', 'Networks and servers that stay up.'], ['Cloud migration', 'Move to Microsoft 365 or Azure.']], pr: [['Office migration', '300 users to Microsoft 365 in a weekend.', 'Azure, M365'], ['Network refresh', 'New Wi-Fi and firewalls for 4 sites.', 'Networking'], ['Help desk revamp', 'Ticket time down 60%.', 'ITIL']], ex: [['IT Manager', 'Northwind Logistics', '2020 – now', 'Team of five, 450 users.'], ['Systems Administrator', 'Infosys', '2015 – 2020', 'Data centre operations.']], st: [['99.9%', 'Uptime'], ['450', 'Users supported'], ['10', 'Years in IT']] },
  'Software Engineer': { k: 'tech', role: 'Software engineer', title: 'Engineering software that scales quietly.', sub: 'Distributed systems, clean APIs and careful code reviews.', about: 'Seven years building backend and product systems at startups and big tech. I enjoy hard problems and simple solutions.', s: 'Java, Go, TypeScript, Kubernetes, PostgreSQL, Kafka', stack: [['Languages', 'Java, Go, TypeScript, Python'], ['Systems', 'Kubernetes, Kafka, gRPC'], ['Data', 'PostgreSQL, Redis, Elasticsearch']], sv: [['System design', 'Architecture that grows with you.'], ['Backend', 'Reliable services and APIs.'], ['Mentoring', 'Help junior engineers level up.']], pr: [['Payments ledger', 'Double-entry ledger, 10k TPS.', 'Go, PostgreSQL'], ['Search revamp', 'P95 latency down 70%.', 'Elasticsearch'], ['Event bus', 'Kafka platform for 40 teams.', 'Kafka, Kubernetes']], ex: [['Senior Engineer', 'Flipkart', '2021 – now', 'Search and discovery.'], ['Software Engineer', 'Razorpay', '2017 – 2021', 'Payments infrastructure.']], st: [['7', 'Years engineering'], ['10k', 'TPS systems'], ['40', 'Teams supported']] },
  'Frontend Developer': { k: 'tech', role: 'Frontend developer', title: 'Interfaces that feel instant.', sub: 'React, Next.js and design systems with obsessive attention to detail.', about: 'I turn designs into fast, accessible interfaces. Six years working closely with designers on products people use every day.', s: 'React, Next.js, TypeScript, Tailwind CSS, Figma, Accessibility', stack: [['Frameworks', 'React, Next.js, Vue'], ['Styling', 'Tailwind CSS, Sass, CSS'], ['Tooling', 'TypeScript, Vite, Jest, Figma']], sv: [['UI development', 'Pixel-perfect, responsive builds.'], ['Design systems', 'Reusable component libraries.'], ['Performance', 'Lighthouse 95+ guaranteed.']], pr: [['Pulse UI', 'Component library used by 30 devs.', 'React, Storybook'], ['Shopfront', 'Next.js store, LCP under 1s.', 'Next.js'], ['A11y audit', 'WCAG AA across a banking app.', 'Accessibility']], ex: [['Senior Frontend Engineer', 'Swiggy', '2022 – now', 'Consumer web app.'], ['Frontend Developer', 'Zeta', '2018 – 2022', 'Design system lead.']], st: [['6', 'Years frontend'], ['98', 'Avg Lighthouse'], ['120+', 'Components built']] },
  'Backend Developer': { k: 'tech', role: 'Backend developer', title: 'APIs and databases that never blink.', sub: 'Node.js, MySQL, queues and caching for high-traffic products.', about: 'I design schemas, write APIs and keep latency low. Six years of backend work for e-commerce and fintech.', s: 'Node.js, Express, MySQL, Redis, Docker, AWS', stack: [['Backend', 'Node.js, Express, NestJS'], ['Data', 'MySQL, PostgreSQL, Redis, MongoDB'], ['Infra', 'Docker, AWS, Nginx, RabbitMQ']], sv: [['API development', 'REST and GraphQL, documented.'], ['Database design', 'Schemas and indexes done right.'], ['Scaling', 'Caching, queues and load tests.']], pr: [['Order service', 'Handles 3M orders a month.', 'Node.js, MySQL'], ['Cache layer', 'DB load down 80% with Redis.', 'Redis'], ['Webhook engine', 'Retries, signing and logs.', 'RabbitMQ']], ex: [['Backend Lead', 'Meesho', '2021 – now', 'Orders and payments.'], ['Backend Developer', 'Dunzo', '2018 – 2021', 'Delivery APIs.']], st: [['6', 'Years backend'], ['3M', 'Orders / month'], ['80%', 'Less DB load']] },
  'Full Stack Developer': { k: 'tech', role: 'Full-stack developer', title: 'From database to button, I build all of it.', sub: 'React and Next.js up front, Node.js, MySQL and AWS behind.', about: 'I take products from idea to launch on my own or with small teams. Five years, 40+ shipped projects.', s: 'React, Next.js, Node.js, MySQL, Docker, AWS', stack: [['Frontend', 'React, Next.js, TypeScript, Tailwind CSS'], ['Backend', 'Node.js, Express, GraphQL'], ['Data & DevOps', 'MySQL, Redis, Docker, AWS']], sv: [['SaaS MVPs', 'Auth, billing and dashboards.'], ['Web apps', 'Full products, end to end.'], ['Maintenance', 'Keep your app fast and secure.']], pr: [['ShipFast', 'SaaS starter used by 300+ teams.', 'Next.js, Stripe'], ['Pulse', 'Real-time analytics dashboard.', 'Node.js, WebSockets'], ['Deployr', 'One-click Docker deploys.', 'Docker, AWS']], ex: [['Full-stack Engineer', 'Paylite', '2023 – now', 'Customer dashboard and APIs.'], ['Freelance Developer', 'Self-employed', '2019 – 2023', '30+ client projects.']], st: [['5', 'Years shipping'], ['40+', 'Projects'], ['300+', 'Teams using my work']] },
  'Mobile App Developer': { k: 'tech', role: 'Mobile app developer', title: 'Apps people keep on their home screen.', sub: 'React Native, Flutter and native iOS/Android with smooth 60fps UIs.', about: 'Six years building consumer and business apps. Three apps featured on the Play Store, one with 2M installs.', s: 'React Native, Flutter, Swift, Kotlin, Firebase, TypeScript', stack: [['Cross-platform', 'React Native, Flutter, Dart'], ['Native', 'Swift, Kotlin'], ['Backend', 'Firebase, Node.js, GraphQL']], sv: [['App development', 'iOS and Android from one codebase.'], ['App Store launch', 'Listings, review and release.'], ['Performance', 'Fix jank, crashes and size.']], pr: [['FitTrack', 'Workout app, 2M installs.', 'Flutter'], ['PayEasy', 'UPI wallet, 4.7★ rating.', 'React Native'], ['Clinic Go', 'Doctor booking app.', 'Swift, Kotlin']], ex: [['Senior Mobile Engineer', 'CRED', '2022 – now', 'Payments experience.'], ['Mobile Developer', 'Practo', '2018 – 2022', 'Patient app.']], st: [['2M+', 'Installs'], ['4.7★', 'Avg rating'], ['12', 'Apps shipped']] },
  'Data Scientist': { k: 'tech', role: 'Data scientist', title: 'Turning data into decisions.', sub: 'Machine learning, experimentation and forecasting that move real metrics.', about: 'I build models that ship, not just notebooks. Six years in e-commerce and fintech data teams.', s: 'Python, Pandas, Scikit-learn, SQL, PyTorch, Statistics', stack: [['Languages', 'Python, SQL, R'], ['ML', 'Scikit-learn, PyTorch, XGBoost'], ['Platform', 'Spark, Airflow, AWS']], sv: [['Predictive models', 'Churn, demand and risk.'], ['Experimentation', 'A/B tests done properly.'], ['Analytics', 'Dashboards that answer questions.']], pr: [['Demand forecast', 'Stock-outs down 35%.', 'Python, XGBoost'], ['Churn model', 'Saved ₹4Cr in retention.', 'Scikit-learn'], ['Pricing engine', 'Margin up 6 points.', 'PyTorch']], ex: [['Senior Data Scientist', 'Myntra', '2021 – now', 'Pricing and forecasting.'], ['Data Scientist', 'PhonePe', '2018 – 2021', 'Fraud models.']], st: [['35%', 'Fewer stock-outs'], ['₹4Cr', 'Retention saved'], ['20+', 'Models in production']] },
  'Data Analyst': { k: 'tech', role: 'Data analyst', title: 'Clear answers from messy data.', sub: 'SQL, dashboards and stories that help teams decide faster.', about: 'I sit between business teams and data. Four years building reports, dashboards and analyses leaders actually read.', s: 'SQL, Excel, Power BI, Tableau, Python, Statistics', stack: [['Analysis', 'SQL, Python, Excel'], ['Visualisation', 'Power BI, Tableau, Looker'], ['Data', 'BigQuery, MySQL, dbt']], sv: [['Dashboards', 'KPIs everyone understands.'], ['Analysis', 'Answers to the hard questions.'], ['Reporting', 'Automated weekly reports.']], pr: [['Sales dashboard', 'Used daily by 80 managers.', 'Power BI'], ['Funnel analysis', 'Found a 22% checkout leak.', 'SQL'], ['Report automation', 'Saved 30 hours a week.', 'Python']], ex: [['Senior Analyst', 'Nykaa', '2022 – now', 'Marketing analytics.'], ['Data Analyst', 'Deloitte', '2020 – 2022', 'Client reporting.']], st: [['80', 'Daily dashboard users'], ['30h', 'Saved weekly'], ['4', 'Years in analytics']] },
  'DevOps Engineer': { k: 'tech', role: 'DevOps engineer', title: 'Ship daily. Sleep at night.', sub: 'CI/CD, Kubernetes and cloud infrastructure that just works.', about: 'I automate deploys, tame cloud bills and set up monitoring that wakes the right person. Seven years in platform teams.', s: 'Docker, Kubernetes, Terraform, AWS, GitHub Actions, Prometheus', stack: [['Containers', 'Docker, Kubernetes, Helm'], ['Cloud & IaC', 'AWS, Terraform, Ansible'], ['CI/CD & Observability', 'GitHub Actions, Jenkins, Grafana']], sv: [['CI/CD', 'Pipelines that deploy in minutes.'], ['Kubernetes', 'Clusters set up and managed.'], ['Cost cuts', 'Lower cloud bills, same speed.']], pr: [['Zero-downtime deploys', '40 services, 30 deploys a day.', 'Kubernetes'], ['Cloud cost cut', 'AWS bill down 42%.', 'AWS, Terraform'], ['Observability', 'Alerts with 90% less noise.', 'Grafana']], ex: [['Senior DevOps Engineer', 'Zomato', '2021 – now', 'Platform team.'], ['DevOps Engineer', 'ThoughtWorks', '2017 – 2021', 'Client platforms.']], st: [['42%', 'Cloud cost saved'], ['30', 'Deploys a day'], ['99.99%', 'Uptime']] },
  Cybersecurity: { k: 'tech', role: 'Security engineer', title: 'Finding the holes before attackers do.', sub: 'Penetration testing, cloud security and incident response.', about: 'Certified ethical hacker with seven years in offensive and defensive security. I explain risks in plain language.', s: 'Penetration testing, OWASP, Burp Suite, SIEM, AWS Security, Python', stack: [['Offensive', 'Burp Suite, Metasploit, Nmap'], ['Defensive', 'SIEM, EDR, Wazuh'], ['Cloud', 'AWS Security, IAM, Terraform']], sv: [['Pen testing', 'Web, API and network tests.'], ['Security audits', 'ISO 27001 and SOC 2 readiness.'], ['Incident response', 'Fast help when things go wrong.']], pr: [['Bank app pentest', '14 critical issues fixed.', 'OWASP'], ['SOC 2 readiness', 'Audit passed first time.', 'Compliance'], ['Bug bounty', 'Hall of fame at 6 companies.', 'Research']], ex: [['Lead Security Engineer', 'Paytm', '2021 – now', 'AppSec team.'], ['Security Consultant', 'EY', '2017 – 2021', 'Pen testing for banks.']], st: [['300+', 'Vulnerabilities found'], ['6', 'Bug bounty halls of fame'], ['OSCP', 'Certified']], extra: 'certs' },
  'AI / ML Engineer': { k: 'tech', role: 'AI / ML engineer', title: 'Shipping AI that is actually useful.', sub: 'LLM apps, retrieval, evals and ML systems in production.', about: 'I build machine learning products end to end: data, models, serving and evaluation. Five years, three AI products launched.', s: 'Python, PyTorch, LLMs, RAG, Vector databases, MLOps', stack: [['Modelling', 'PyTorch, Transformers, Scikit-learn'], ['LLM apps', 'RAG, Embeddings, Evals'], ['Serving', 'FastAPI, Docker, Kubernetes']], sv: [['LLM apps', 'Chatbots and copilots on your data.'], ['ML systems', 'Models from notebook to production.'], ['Evaluation', 'Know if your AI is any good.']], pr: [['Support copilot', 'Resolved 40% of tickets.', 'RAG, LLM'], ['Doc search', 'Semantic search over 2M docs.', 'Embeddings'], ['Vision QA', 'Factory defect detection.', 'PyTorch']], ex: [['ML Engineer', 'Sarvam AI', '2023 – now', 'LLM applications.'], ['Data Scientist', 'Ola', '2019 – 2023', 'Pricing models.']], st: [['40%', 'Tickets auto-resolved'], ['2M', 'Docs indexed'], ['3', 'AI products launched']] },
  'QA Tester': { k: 'tech', role: 'QA engineer', title: 'Bugs stop here.', sub: 'Manual and automated testing for web and mobile apps.', about: 'Five years making sure releases go out clean. I write test plans, automate the boring parts and speak up early.', s: 'Selenium, Cypress, Playwright, Postman, JIRA, Manual testing', stack: [['Automation', 'Cypress, Playwright, Selenium'], ['API', 'Postman, REST Assured'], ['Process', 'JIRA, TestRail, CI']], sv: [['Test automation', 'Suites that run on every commit.'], ['Manual testing', 'Exploratory and regression.'], ['QA process', 'Test plans and release checklists.']], pr: [['E2E suite', '600 tests, 8-minute runs.', 'Playwright'], ['API tests', 'Contract tests for 90 endpoints.', 'Postman'], ['Release process', 'Production bugs down 70%.', 'Process']], ex: [['QA Lead', 'Freshworks', '2022 – now', 'Web and mobile QA.'], ['QA Engineer', 'Wipro', '2019 – 2022', 'Banking clients.']], st: [['70%', 'Fewer prod bugs'], ['600', 'Automated tests'], ['5', 'Years in QA']] },
  'Product Manager': { k: 'business', role: 'Product manager', title: 'Building products people love to use.', sub: 'Discovery, roadmaps and launches for B2B and consumer SaaS.', about: 'Seven years turning customer problems into shipped features. I write clear specs and make hard trade-offs early.', s: 'Product strategy, Roadmapping, User research, Analytics, Agile, SQL', sv: [['Product strategy', 'Vision, roadmap and metrics.'], ['Discovery', 'Research that finds real problems.'], ['Launches', 'Go-to-market that lands.']], pr: [['Onboarding revamp', 'Activation up 34%.', 'Growth'], ['Pricing launch', 'ARPU up 18%.', 'Monetisation'], ['Mobile app', '0 to 500k users.', 'Consumer']], ex: [['Senior PM', 'Freshworks', '2021 – now', 'CRM product line.'], ['Product Manager', 'Zoho', '2017 – 2021', 'Mobile apps.']], st: [['34%', 'Activation lift'], ['500k', 'Users reached'], ['25', 'Launches']], work: 'projects', extra: 'logos' },

  Designer: { k: 'visual', role: 'Product designer', title: 'I design calm software for busy people.', sub: 'Eight years shaping apps for fintech and health teams.', about: 'I start with research and end with pixels. I like clear language, fast interfaces and teams that ship.', s: 'Product design, Prototyping, User research, Design systems, Figma', sv: [['Product design', 'From research to polished UI.'], ['Design systems', 'Components your team will use.'], ['Prototyping', 'Clickable ideas within days.']], pr: [['Budget Buddy', 'Personal finance app.', 'Mobile, Fintech'], ['CareConnect', 'Patient portal redesign.', 'Health, Web'], ['Atlas DS', 'Design system for 6 products.', 'Systems']], ex: [['Lead Designer', 'Northwind', '2022 – now', 'Payments platform.'], ['Product Designer', 'Brightloop', '2018 – 2022', 'Mobile app to 1M users.']], st: [['8+', 'Years designing'], ['60', 'Products shipped'], ['1M', 'Users reached']], work: 'projects', extra: 'logos' },
  'Graphic Designer': { k: 'visual', role: 'Graphic designer', title: 'Design that makes people stop scrolling.', sub: 'Logos, packaging, posters and social creatives.', about: 'I have designed for cafés, startups and festivals for seven years. Bold colour, strong type, no clutter.', s: 'Branding, Typography, Packaging, Adobe Illustrator, Photoshop', sv: [['Logo & brand', 'Identity kits that last.'], ['Packaging', 'Boxes and labels that sell.'], ['Social creatives', 'Monthly post packs.']], pr: [['Chai Point', 'Cup and packaging design.', 'Packaging'], ['Jaipur Lit Fest', 'Poster series.', 'Print'], ['Bloom', 'Brand identity.', 'Branding']], ex: [['Senior Designer', 'Ogilvy', '2021 – now', 'FMCG brands.'], ['Graphic Designer', 'Freelance', '2017 – 2021', '80+ clients.']], st: [['7', 'Years designing'], ['300+', 'Logos made'], ['80', 'Happy clients']], work: 'gallery', extra: 'logos' },
  'UI/UX Designer': { k: 'visual', role: 'UI/UX designer', title: 'Interfaces that feel like a friendly nudge.', sub: 'Research-led UX and polished UI for mobile and web apps.', about: 'I talk to users, sketch flows and test early. Five years designing apps across fintech, edtech and health.', s: 'User research, Wireframing, UI design, Prototyping, Figma, Usability testing', sv: [['UX research', 'Interviews and usability tests.'], ['UI design', 'Clean, consistent screens.'], ['Prototypes', 'Test ideas before building.']], pr: [['Plant Pal', 'Plant care app case study.', 'Mobile, Research'], ['Study Sprint', 'Edtech dashboard.', 'Web'], ['Quick Pay', 'Checkout redesign, +30% conversion.', 'Fintech']], ex: [['UX Designer', 'Unacademy', '2022 – now', 'Learner experience.'], ['UI Designer', 'Freelance', '2019 – 2022', 'Startups.']], st: [['30%', 'Conversion lift'], ['50+', 'Usability tests'], ['5', 'Years in UX']], work: 'projects', extra: 'faq' },
  'Web Designer': { k: 'visual', role: 'Web designer', title: 'Websites that look good and load fast.', sub: 'Custom websites for small businesses, built in Webflow and WordPress.', about: 'I design and build websites for cafés, clinics and consultants. Six years, 150 sites launched.', s: 'Web design, Webflow, WordPress, SEO basics, Figma, Responsive design', sv: [['Website design', 'Custom, mobile-first sites.'], ['Webflow builds', 'Easy for you to edit.'], ['Redesigns', 'Make your old site new.']], pr: [['Brew Lab', 'Café website with online orders.', 'Webflow'], ['Smile Clinic', 'Dental clinic site.', 'WordPress'], ['Studio K', 'Architecture portfolio.', 'Webflow']], ex: [['Founder', 'Pixel Studio', '2020 – now', 'Small web studio.'], ['Web Designer', 'WebChutney', '2017 – 2020', 'Agency projects.']], st: [['150', 'Sites launched'], ['95', 'Avg PageSpeed'], ['6', 'Years designing']], work: 'projects', extra: 'pricing' },
  Illustrator: { k: 'visual', role: 'Illustrator', title: 'Drawings with a story in every corner.', sub: 'Editorial, children’s books and brand illustration.', about: 'I draw every day, mostly with a pencil and a tablet. My work has appeared in books, magazines and on packaging.', s: 'Editorial illustration, Character design, Procreate, Watercolour, Lettering', sv: [['Editorial', 'Illustrations for articles.'], ['Children’s books', 'Characters and full books.'], ['Brand art', 'Murals, packaging and merch.']], pr: [['The Little Kite', 'Picture book, 32 pages.', 'Books'], ['Monsoon diaries', 'Magazine series.', 'Editorial'], ['Café mural', '12-metre wall.', 'Mural']], ex: [['Freelance Illustrator', 'Self-employed', '2018 – now', 'Books and brands.'], ['Illustrator', 'Tinkle', '2015 – 2018', 'Comics team.']], st: [['9', 'Books illustrated'], ['40', 'Magazine covers'], ['10', 'Years drawing']], work: 'gallery', extra: 'logos' },
  Animator: { k: 'visual', role: 'Motion designer', title: 'Making brands move.', sub: '2D animation, explainers and motion graphics for products and ads.', about: 'I bring logos, products and ideas to life frame by frame. Seven years in studios and agencies.', s: 'After Effects, Character animation, Explainers, Cinema 4D, Storyboarding', sv: [['Explainer videos', 'Complex ideas in 60 seconds.'], ['Logo animation', 'Intros that stick.'], ['Social motion', 'Scroll-stopping loops.']], pr: [['Fintech explainer', '2M views on YouTube.', 'Explainer'], ['Festival idents', 'TV channel idents.', 'Broadcast'], ['App onboarding', 'Animated walkthrough.', 'Product']], ex: [['Senior Animator', 'Toonz Media', '2021 – now', 'Series and ads.'], ['Motion Designer', 'Freelance', '2017 – 2021', 'Agencies and startups.']], st: [['2M', 'Views on one video'], ['150', 'Animations made'], ['7', 'Years animating']], work: 'gallery', extra: 'video' },
  'Video Editor': { k: 'visual', role: 'Video editor', title: 'Edits that keep people watching.', sub: 'YouTube, ads and documentaries with tight pacing and clean colour.', about: 'I have edited for YouTubers with millions of subscribers and brands you know. Story first, effects second.', s: 'Premiere Pro, DaVinci Resolve, Colour grading, Sound design, Storytelling', sv: [['YouTube editing', 'Retention-focused edits.'], ['Ads & reels', 'Short, punchy, on-brand.'], ['Colour grading', 'A consistent cinematic look.']], pr: [['Travel series', '12 episodes, 8M views.', 'YouTube'], ['Brand film', 'Launch film for a D2C brand.', 'Commercial'], ['Documentary', 'Festival selection.', 'Film']], ex: [['Lead Editor', 'Filter Copy', '2021 – now', 'Branded content.'], ['Video Editor', 'Freelance', '2017 – 2021', 'YouTube creators.']], st: [['50M', 'Views edited'], ['400+', 'Videos'], ['7', 'Years editing']], work: 'gallery', extra: 'video' },
  Photographer: { k: 'visual', role: 'Photographer', title: 'Photographs that feel like being there.', sub: 'Portraits, products and events with natural light and honest moments.', about: 'I have been photographing people and products for ten years. Calm on set, quick with delivery.', s: 'Portraits, Product photography, Events, Lightroom, Studio lighting', sv: [['Portraits', 'Headshots and personal shoots.'], ['Products', 'E-commerce and lifestyle.'], ['Events', 'Weddings, launches, parties.']], pr: [['Faces of Jaipur', 'Portrait series.', 'Portrait'], ['Kettle & Co', 'Product catalogue.', 'Product'], ['TEDx Pune', 'Event coverage.', 'Event']], ex: [['Photographer', 'Self-employed', '2016 – now', 'Portraits and brands.'], ['Studio Assistant', 'Lightbox Studio', '2013 – 2016', 'Lighting and retouching.']], st: [['10', 'Years shooting'], ['500+', 'Shoots'], ['24h', 'Preview delivery']], work: 'gallery', extra: 'pricing' },
  Videographer: { k: 'visual', role: 'Videographer', title: 'Films for weddings, brands and stories.', sub: 'Cinematic video from first frame to final cut.', about: 'I shoot and edit films with a small crew and a lot of care. Eight years, from weddings to brand launches.', s: 'Cinematography, Drone, Editing, Colour grading, Sound', sv: [['Wedding films', 'Your day as a short film.'], ['Brand films', 'Stories that sell.'], ['Drone shoots', 'Aerial footage, licensed.']], pr: [['Goa wedding', 'Beach wedding film.', 'Wedding'], ['Organic farm', 'Brand documentary.', 'Brand'], ['City from above', 'Drone showreel.', 'Drone']], ex: [['Founder', 'Frame Story Films', '2018 – now', 'Team of four.'], ['Camera Operator', 'Zee Studios', '2015 – 2018', 'TV productions.']], st: [['150', 'Weddings filmed'], ['8', 'Years filming'], ['4K', 'Delivered']], work: 'gallery', extra: 'video' },
  'Interior Designer': { k: 'visual', role: 'Interior designer', title: 'Spaces that feel like you.', sub: 'Homes, cafés and offices designed with warmth and purpose.', about: 'I design interiors that are beautiful to live in and easy to maintain. Nine years, 120 spaces completed.', s: 'Space planning, 3D visualisation, Material selection, AutoCAD, SketchUp', sv: [['Home interiors', 'Full design and execution.'], ['Commercial', 'Cafés, offices and studios.'], ['Consultation', 'A one-day design plan.']], pr: [['Courtyard home', '4BHK in Jaipur.', 'Residential'], ['Brew Lab café', 'Industrial café fit-out.', 'Commercial'], ['Studio office', 'Office for 40 people.', 'Workplace']], ex: [['Principal Designer', 'Nest Interiors', '2019 – now', 'Residential and commercial.'], ['Interior Designer', 'Livspace', '2015 – 2019', 'Home projects.']], st: [['120', 'Spaces designed'], ['9', 'Years practice'], ['15', 'Cities']], work: 'gallery', extra: 'pricing' },
  'Fashion Designer': { k: 'visual', role: 'Fashion designer', title: 'Handwoven textiles, modern silhouettes.', sub: 'Small-batch collections made with weavers across Rajasthan.', about: 'I design clothes that last, made slowly by artisans I know by name. Showcased at Lakmé Fashion Week.', s: 'Pattern making, Textiles, Draping, Sustainable fashion, Illustration', sv: [['Collections', 'Seasonal ready-to-wear.'], ['Bridal', 'Made-to-measure couture.'], ['Styling', 'Shoots and personal styling.']], pr: [['Indigo', 'Spring collection.', 'Collection'], ['Bandhej revival', 'Artisan collaboration.', 'Craft'], ['LFW 2025', 'Runway show.', 'Runway']], ex: [['Founder', 'Ananya Atelier', '2019 – now', 'Label and studio.'], ['Designer', 'Fabindia', '2015 – 2019', 'Womenswear.']], st: [['8', 'Collections'], ['40', 'Artisans'], ['1', 'Fashion week']], work: 'gallery', extra: 'logos' },
  Architect: { k: 'visual', role: 'Architect', title: 'Buildings shaped by light and climate.', sub: 'Residential and public architecture rooted in place.', about: 'I design climate-responsive buildings using local materials. Twelve years of practice, 60 projects built.', s: 'Architectural design, Revit, AutoCAD, Sustainable design, Rhino', sv: [['Residential', 'Homes designed for how you live.'], ['Public', 'Schools, libraries, community spaces.'], ['Masterplanning', 'Campuses and neighbourhoods.']], pr: [['Stone House', 'Courtyard home in Jodhpur.', 'Residential'], ['Village school', 'Passive-cooled school.', 'Public'], ['Riverfront', 'Public promenade.', 'Urban']], ex: [['Principal Architect', 'Studio Earth', '2017 – now', 'Own practice.'], ['Architect', 'Morphogenesis', '2012 – 2017', 'Large projects.']], st: [['60', 'Projects built'], ['12', 'Years practice'], ['5', 'Design awards']], work: 'gallery', extra: 'logos' },
  Artist: { k: 'visual', role: 'Visual artist', title: 'Paintings about memory and home.', sub: 'Oil and mixed media works shown in Mumbai, Delhi and Berlin.', about: 'I paint the places I grew up in, as I remember them rather than as they were. Eleven solo shows so far.', s: 'Oil painting, Mixed media, Installation, Printmaking, Curation', sv: [['Original works', 'Paintings for collectors.'], ['Commissions', 'Portraits and murals.'], ['Workshops', 'Painting classes for adults.']], pr: [['Monsoon rooms', 'Solo show, Mumbai.', 'Exhibition'], ['Salt and lime', 'Installation, Berlin.', 'Installation'], ['Grandmother’s house', 'Series of 12 paintings.', 'Series']], ex: [['Artist', 'Studio practice', '2014 – now', 'Paintings and installations.'], ['Resident', 'Khoj Studios', '2013', 'Artist residency.']], st: [['11', 'Solo shows'], ['200+', 'Works sold'], ['4', 'Countries']], work: 'gallery', extra: 'faq' },
  Musician: { k: 'visual', role: 'Musician & composer', title: 'Songs for late nights and long drives.', sub: 'Singer-songwriter and film composer. New single out now.', about: 'I write, record and perform indie-folk music in Hindi and English. Two albums, 300 shows, one very old guitar.', s: 'Songwriting, Composition, Guitar, Production, Live performance', sv: [['Live shows', 'Concerts, weddings and events.'], ['Film scores', 'Music for films and ads.'], ['Production', 'Record your songs with me.']], pr: [['Ghar', 'Debut album, 5M streams.', 'Album'], ['Monsoon songs', 'EP for a web series.', 'Score'], ['Unplugged tour', '30 cities.', 'Live']], ex: [['Independent artist', 'Self-released', '2017 – now', 'Two albums.'], ['Composer', 'Yash Raj Films', '2020 – 2022', 'Background scores.']], st: [['5M', 'Streams'], ['300', 'Live shows'], ['2', 'Albums']], work: 'gallery', extra: 'video' },

  Sales: { k: 'business', role: 'Sales leader', title: 'Building revenue teams that hit their number.', sub: 'B2B sales, pipeline and team building for SaaS companies.', about: 'Twelve years in B2B sales, from first rep to VP. I build repeatable playbooks and coach people to close.', s: 'B2B sales, Negotiation, Salesforce, Team leadership, Forecasting', sv: [['Sales strategy', 'Playbooks that scale.'], ['Team building', 'Hire and coach great reps.'], ['Enterprise deals', 'Close the big ones.']], pr: [['₹100Cr ARR', 'Grew region from ₹20Cr.', 'Growth'], ['New market', 'Opened South-East Asia.', 'Expansion'], ['Playbook', 'Ramp time down 40%.', 'Enablement']], ex: [['VP Sales', 'Freshworks', '2020 – now', 'APAC region.'], ['Sales Manager', 'Salesforce', '2014 – 2020', 'Enterprise accounts.']], st: [['₹100Cr', 'ARR built'], ['140%', 'Avg quota'], ['60', 'Reps coached']], work: 'projects', extra: 'logos' },
  Marketing: { k: 'business', role: 'Marketing lead', title: 'Brands people remember. Growth you can measure.', sub: 'Brand, campaigns and growth marketing for consumer brands.', about: 'Ten years across brand and performance marketing. I balance big ideas with spreadsheets.', s: 'Brand strategy, Campaigns, Growth, Analytics, Content', sv: [['Brand strategy', 'Positioning and messaging.'], ['Campaigns', 'Launches that get noticed.'], ['Growth', 'Channels that scale.']], pr: [['Monsoon campaign', '40M impressions.', 'Campaign'], ['Rebrand', 'Awareness up 3×.', 'Brand'], ['App launch', '1M downloads in 90 days.', 'Growth']], ex: [['Head of Marketing', 'boAt', '2021 – now', 'Brand and growth.'], ['Brand Manager', 'HUL', '2015 – 2021', 'Personal care.']], st: [['3×', 'Brand awareness'], ['40M', 'Campaign reach'], ['10', 'Years marketing']], work: 'projects', extra: 'logos' },
  'Digital Marketing': { k: 'business', role: 'Digital marketer', title: 'More leads, lower cost, clear reports.', sub: 'Google Ads, Meta Ads and funnels for growing businesses.', about: 'I have managed ₹50Cr in ad spend across e-commerce, education and real estate. Every rupee tracked.', s: 'Google Ads, Meta Ads, Analytics, Funnels, Email marketing', sv: [['Paid ads', 'Google and Meta campaigns.'], ['Funnels', 'Landing pages that convert.'], ['Analytics', 'Tracking set up right.']], pr: [['Edtech leads', 'Cost per lead down 55%.', 'Meta Ads'], ['D2C store', 'ROAS 4.8×.', 'Google Ads'], ['Real estate', '1,200 site visits.', 'Funnels']], ex: [['Performance Lead', 'Social Beat', '2021 – now', '30 accounts.'], ['Digital Marketer', 'Freelance', '2018 – 2021', 'Small businesses.']], st: [['₹50Cr', 'Ad spend managed'], ['4.8×', 'Best ROAS'], ['55%', 'Lower CPL']], work: 'projects', extra: 'pricing' },
  'Social Media Manager': { k: 'business', role: 'Social media manager', title: 'Content that grows communities.', sub: 'Strategy, content and community for Instagram, LinkedIn and YouTube.', about: 'I have grown brand accounts from zero to hundreds of thousands. Trends, tone and timing are my thing.', s: 'Content strategy, Instagram, LinkedIn, Reels, Community, Analytics', sv: [['Strategy', 'Monthly plans and calendars.'], ['Content', 'Reels, carousels, captions.'], ['Community', 'Replies, DMs and creators.']], pr: [['Café brand', '0 to 120k followers.', 'Instagram'], ['Founder LinkedIn', '8M impressions.', 'LinkedIn'], ['Creator campaign', '50 creators, one launch.', 'Influencer']], ex: [['Social Lead', 'Chumbak', '2021 – now', 'All channels.'], ['Social Executive', 'Agency', '2018 – 2021', 'FMCG clients.']], st: [['120k', 'Followers grown'], ['8M', 'Impressions'], ['50', 'Creators managed']], work: 'gallery', extra: 'pricing' },
  'Content Writer': { k: 'business', role: 'Content writer', title: 'Words that rank, read well and sell.', sub: 'Blogs, website copy and long-form content for B2B and SaaS.', about: 'Six years writing for SaaS and tech brands. Researched, readable and on deadline every time.', s: 'Blog writing, SEO writing, Research, Editing, Content strategy', sv: [['Blog posts', 'SEO-friendly long-form.'], ['Website copy', 'Clear pages that convert.'], ['Ebooks', 'Lead magnets and guides.']], pr: [['SaaS blog', 'Traffic 10× in a year.', 'SEO'], ['Fintech guide', '20k downloads.', 'Ebook'], ['Website rewrite', 'Sign-ups up 25%.', 'Copy']], ex: [['Senior Writer', 'Freshworks', '2021 – now', 'Blog and guides.'], ['Content Writer', 'Freelance', '2018 – 2021', '40 clients.']], st: [['600+', 'Articles'], ['10×', 'Traffic growth'], ['40', 'Clients']], work: 'projects', extra: 'faq' },
  Copywriter: { k: 'business', role: 'Copywriter', title: 'Copy that makes people click, buy and smile.', sub: 'Ads, taglines, websites and product copy with a voice.', about: 'Eight years in advertising and brand writing. I find the one line that says it all.', s: 'Advertising, Taglines, UX writing, Brand voice, Scripts', sv: [['Ad copy', 'Print, digital and TV.'], ['Brand voice', 'How your brand should sound.'], ['UX writing', 'Microcopy that helps.']], pr: [['Tea brand', 'Tagline used for 5 years.', 'Brand'], ['App store', 'Installs up 30%.', 'UX'], ['TV spot', '30-second script.', 'Advertising']], ex: [['Senior Copywriter', 'Leo Burnett', '2020 – now', 'FMCG and auto.'], ['Copywriter', 'Wieden+Kennedy', '2016 – 2020', 'Sports brands.']], st: [['8', 'Years writing'], ['12', 'Ad awards'], ['30%', 'Install lift']], work: 'projects', extra: 'logos' },
  'SEO Specialist': { k: 'business', role: 'SEO specialist', title: 'Get found on Google. Stay there.', sub: 'Technical SEO, content and links for websites that want organic growth.', about: 'Seven years helping sites climb search rankings without tricks. Audits, fixes and content plans.', s: 'Technical SEO, Keyword research, Link building, Google Search Console, Ahrefs', sv: [['SEO audits', 'Find what is holding you back.'], ['Technical SEO', 'Speed, schema and indexing.'], ['Content plans', 'Keywords that bring buyers.']], pr: [['Travel site', 'Organic traffic 6×.', 'Content'], ['E-commerce', '1,400 keywords on page 1.', 'Technical'], ['Local clinic', 'Top 3 in Maps.', 'Local SEO']], ex: [['SEO Lead', 'MakeMyTrip', '2021 – now', 'Organic growth.'], ['SEO Consultant', 'Freelance', '2017 – 2021', 'SMBs.']], st: [['6×', 'Traffic growth'], ['1,400', 'Page-1 keywords'], ['7', 'Years in SEO']], work: 'projects', extra: 'pricing' },
  HR: { k: 'business', role: 'HR leader', title: 'Great teams, built on purpose.', sub: 'Hiring, culture and people operations for fast-growing companies.', about: 'Eleven years in people teams, from startups to large enterprises. I hire well and help people grow.', s: 'Talent acquisition, Employee engagement, HR policy, Payroll, L&D', sv: [['Hiring', 'Find and close great people.'], ['Culture', 'Engagement that is real.'], ['HR setup', 'Policies, payroll and tools.']], pr: [['Scale-up hiring', '300 hires in a year.', 'Talent'], ['Engagement', 'eNPS from 12 to 48.', 'Culture'], ['HR system', 'Moved to one HRMS.', 'Ops']], ex: [['Head of People', 'Groww', '2021 – now', '1,200 employees.'], ['HR Manager', 'Accenture', '2014 – 2021', 'Business HR.']], st: [['300', 'Hires a year'], ['48', 'eNPS'], ['11', 'Years in HR']], work: 'projects', extra: 'logos' },
  Finance: { k: 'business', role: 'Finance professional', title: 'Numbers you can trust and act on.', sub: 'FP&A, fundraising and financial strategy for growing companies.', about: 'Chartered accountant and former investment banker. I help founders understand and grow their numbers.', s: 'Financial modelling, FP&A, Valuation, Fundraising, Excel', sv: [['Financial models', 'Forecasts investors trust.'], ['Fundraising', 'Decks, data rooms and terms.'], ['Fractional CFO', 'Finance leadership, part-time.']], pr: [['Series B', 'Raised ₹200Cr.', 'Fundraising'], ['Cost review', 'Burn down 30%.', 'FP&A'], ['Acquisition', 'Led due diligence.', 'M&A']], ex: [['CFO', 'Zetwerk', '2021 – now', 'Finance and strategy.'], ['Associate', 'Kotak Investment Banking', '2015 – 2021', 'Tech deals.']], st: [['₹500Cr', 'Capital raised'], ['30%', 'Burn reduced'], ['CA', 'Qualified']], work: 'projects', extra: 'logos' },
  Accountant: { k: 'business', role: 'Chartered accountant', title: 'Books in order. Taxes on time.', sub: 'Accounting, GST and tax filing for businesses and individuals.', about: 'Twelve years helping small businesses and families stay compliant and save tax legally.', s: 'Bookkeeping, GST, Income tax, Audit, Tally, Zoho Books', sv: [['Bookkeeping', 'Monthly books, done.'], ['GST & tax', 'Filing and planning.'], ['Audit', 'Statutory and internal.']], pr: [['Retail chain', 'GST compliance for 20 stores.', 'GST'], ['Startup', 'Books and audit for a funded startup.', 'Audit'], ['Families', 'Tax planning for 300 households.', 'Tax']], ex: [['Partner', 'Mehta & Co.', '2016 – now', 'Own practice.'], ['Senior Associate', 'KPMG', '2012 – 2016', 'Audit.']], st: [['500+', 'Clients'], ['12', 'Years practice'], ['100%', 'On-time filing']], work: 'projects', extra: 'pricing' },
  Consultant: { k: 'business', role: 'Management consultant', title: 'Clear strategy for hard decisions.', sub: 'Strategy, operations and transformation for leadership teams.', about: 'Former McKinsey consultant with ten years advising boards and leadership teams across Asia.', s: 'Strategy, Transformation, Operations, Market research, Workshops', sv: [['Strategy', 'Choices you can defend.'], ['Transformation', 'Change that sticks.'], ['Workshops', 'Align leadership in a day.']], pr: [['Bank strategy', 'Five-year growth plan.', 'Strategy'], ['Factory ops', 'Output up 22%.', 'Operations'], ['Market study', 'Entry into Indonesia.', 'Research']], ex: [['Independent Consultant', 'Self-employed', '2021 – now', 'Strategy advisory.'], ['Engagement Manager', 'McKinsey & Company', '2014 – 2021', 'Financial services.']], st: [['60', 'Engagements'], ['10', 'Years advising'], ['12', 'Countries']], work: 'projects', extra: 'logos' },
  Entrepreneur: { k: 'business', role: 'Founder', title: 'Building companies that solve real problems.', sub: 'Two-time founder. Currently building in climate tech.', about: 'I started my first company in college and sold my second in 2023. Now building tools to cut industrial emissions.', s: 'Leadership, Fundraising, Product, Hiring, Go-to-market', sv: [['Advising', 'Help early founders avoid my mistakes.'], ['Investing', 'Angel cheques in climate and SaaS.'], ['Speaking', 'Talks on building startups.']], pr: [['GreenGrid', 'Climate tech, Series A.', 'Current'], ['ShopEasy', 'Acquired in 2023.', 'Exit'], ['Angel portfolio', '18 startups.', 'Investing']], ex: [['Founder & CEO', 'GreenGrid', '2023 – now', 'Climate tech.'], ['Co-founder', 'ShopEasy', '2016 – 2023', 'Acquired by a unicorn.']], st: [['2', 'Companies founded'], ['1', 'Exit'], ['18', 'Angel investments']], work: 'projects', extra: 'logos' },
  'Real Estate Agent': { k: 'business', role: 'Real estate advisor', title: 'Find the right home, at the right price.', sub: 'Buying, selling and renting homes across Jaipur and Delhi NCR.', about: 'Nine years helping families and investors find property. Honest advice, no pressure, every document checked.', s: 'Residential sales, Negotiation, Property valuation, Legal checks, Rentals', sv: [['Buying', 'Shortlist, visit and negotiate.'], ['Selling', 'Get the best price, fast.'], ['Rentals', 'Tenants and landlords matched.']], pr: [['Luxury villa', 'Sold in 18 days.', 'Sales'], ['First home', '120 families helped.', 'Buying'], ['Commercial lease', 'Office for 200 seats.', 'Commercial']], ex: [['Founder', 'Keystone Realty', '2019 – now', 'Team of eight.'], ['Senior Agent', 'Anarock', '2015 – 2019', 'Residential sales.']], st: [['₹300Cr', 'Property sold'], ['400', 'Happy families'], ['9', 'Years advising']], work: 'gallery', extra: 'map' },
  Lawyer: { k: 'business', role: 'Advocate', title: 'Clear legal advice. Strong representation.', sub: 'Corporate, property and family law. High Court and Supreme Court.', about: 'Fourteen years of practice. I explain the law plainly and fight hard when it matters.', s: 'Corporate law, Property law, Litigation, Contracts, Family law', sv: [['Corporate', 'Contracts, compliance and disputes.'], ['Property', 'Titles, sales and disputes.'], ['Family', 'Sensitive matters, handled with care.']], pr: [['Startup counsel', '40 startups advised.', 'Corporate'], ['Land dispute', 'Won a 12-year case.', 'Litigation'], ['M&A', 'Acquisition documentation.', 'Transactions']], ex: [['Founding Partner', 'Rao Legal', '2017 – now', 'Own chambers.'], ['Associate', 'Cyril Amarchand Mangaldas', '2010 – 2017', 'Corporate.']], st: [['14', 'Years practice'], ['600+', 'Matters'], ['40', 'Startups advised']], work: 'projects', extra: 'faq' },
  'Customer Support': { k: 'business', role: 'Customer support lead', title: 'Turning frustrated customers into fans.', sub: 'Support operations, help centres and teams that care.', about: 'Eight years leading support teams for SaaS and e-commerce. Fast replies, kind words, fewer tickets.', s: 'Zendesk, Freshdesk, Team leadership, Knowledge bases, CSAT', sv: [['Support setup', 'Tools, SLAs and workflows.'], ['Help centres', 'Self-serve articles.'], ['Team training', 'Tone, empathy and speed.']], pr: [['CSAT lift', 'From 78% to 95%.', 'Quality'], ['Help centre', 'Tickets down 35%.', 'Self-serve'], ['24/7 team', 'Built a team of 40.', 'Operations']], ex: [['Support Lead', 'Razorpay', '2021 – now', 'Merchant support.'], ['Team Lead', 'Amazon', '2016 – 2021', 'Customer service.']], st: [['95%', 'CSAT'], ['35%', 'Fewer tickets'], ['40', 'Agents led']], work: 'projects', extra: 'faq' },

  Teacher: { k: 'people', role: 'Teacher', title: 'Making maths click for every student.', sub: 'Classes for grades 8–12 and JEE foundation. Online and in Jaipur.', about: 'I have taught maths for twelve years. I believe every student can love it with the right explanation.', s: 'Mathematics, Physics, Lesson planning, Online teaching, Mentoring', sv: [['Group classes', 'Small batches, big attention.'], ['One-on-one', 'Personal tutoring.'], ['Exam prep', 'Boards and JEE foundation.']], pr: [['Board results', '40 students scored 95+.', 'Results'], ['YouTube channel', '80k subscribers.', 'Online'], ['Workbook', 'Practice book for grade 10.', 'Book']], ex: [['Senior Teacher', 'DPS Jaipur', '2016 – now', 'Mathematics, grades 9–12.'], ['Teacher', 'Kendriya Vidyalaya', '2012 – 2016', 'Middle school.']], st: [['12', 'Years teaching'], ['2,000+', 'Students'], ['80k', 'YouTube subscribers']], work: 'projects', extra: 'education' },
  Student: { k: 'people', role: 'Computer science student', title: 'Learning fast and building things.', sub: 'Final-year B.Tech student looking for internships in software development.', about: 'I love solving problems with code. Hackathons, open source and a few apps my friends actually use.', s: 'Python, Java, React, DSA, SQL, Git', sv: [['Projects', 'Web apps and tools I have built.'], ['Hackathons', '6 hackathons, 2 wins.'], ['Open source', 'Contributions on GitHub.']], pr: [['Campus Eats', 'Food ordering for my hostel.', 'React, Firebase'], ['Study Buddy', 'Hackathon-winning study app.', 'Python'], ['DSA notes', '300 problems with solutions.', 'Java']], ex: [['Software Intern', 'Zoho', 'Summer 2026', 'Built internal tools.'], ['Club Lead', 'Coding Club', '2024 – now', 'Weekly contests.']], st: [['8.9', 'CGPA'], ['2', 'Hackathon wins'], ['400+', 'LeetCode problems']], work: 'projects', extra: 'education' },
  Doctor: { k: 'people', role: 'Consultant physician', title: 'Care that listens first.', sub: 'Internal medicine and diabetes care in Jaipur. Online consultations available.', about: 'MBBS, MD (Medicine) with fifteen years of practice. I take time to explain your health and your options.', s: 'Internal medicine, Diabetes, Hypertension, Preventive care, Telemedicine', sv: [['Consultations', 'In clinic or online.'], ['Diabetes care', 'Long-term management plans.'], ['Health checks', 'Preventive packages.']], pr: [['Diabetes camp', '2,000 people screened.', 'Community'], ['Research', '12 published papers.', 'Research'], ['Clinic', 'Opened a family clinic.', 'Practice']], ex: [['Consultant', 'Fortis Hospital', '2016 – now', 'Internal medicine.'], ['Resident', 'AIIMS Delhi', '2010 – 2016', 'MD Medicine.']], st: [['15', 'Years practice'], ['20k+', 'Patients'], ['12', 'Papers']], work: 'projects', extra: 'map' },
  Nurse: { k: 'people', role: 'Registered nurse', title: 'Compassionate care, every shift.', sub: 'ICU and home care nursing with ten years of experience.', about: 'I have worked in ICUs and home care for ten years. Calm, careful and always on the patient’s side.', s: 'Critical care, Patient care, IV therapy, Wound care, BLS/ACLS', sv: [['Home care', 'Skilled nursing at home.'], ['Elderly care', 'Daily support and monitoring.'], ['Post-surgery', 'Recovery care and dressing.']], pr: [['ICU team', 'Led a 12-bed ICU shift.', 'Critical care'], ['Training', 'Trained 40 new nurses.', 'Education'], ['Covid ward', 'Frontline service 2020–21.', 'Service']], ex: [['Senior Nurse', 'Apollo Hospitals', '2018 – now', 'ICU.'], ['Staff Nurse', 'Manipal Hospital', '2014 – 2018', 'General ward.']], st: [['10', 'Years nursing'], ['40', 'Nurses trained'], ['24/7', 'Home care']], work: 'projects', extra: 'faq' },
  'Fitness Trainer': { k: 'people', role: 'Fitness coach', title: 'Get strong. Feel great. Stay consistent.', sub: 'Personal training and online coaching for busy people.', about: 'Certified strength coach with eight years of experience. Simple plans, real food, steady progress.', s: 'Strength training, Nutrition, Weight loss, Mobility, Online coaching', sv: [['Personal training', 'One-on-one at the gym.'], ['Online coaching', 'Plans, check-ins and chat.'], ['Nutrition', 'Simple meal plans.']], pr: [['12-week program', '300 transformations.', 'Program'], ['Corporate wellness', 'Sessions for 4 companies.', 'Corporate'], ['Marathon prep', '50 runners coached.', 'Running']], ex: [['Head Coach', 'Cult.fit', '2020 – now', 'Strength programs.'], ['Trainer', 'Gold’s Gym', '2016 – 2020', 'Personal training.']], st: [['300+', 'Transformations'], ['8', 'Years coaching'], ['4.9★', 'Client rating']], work: 'gallery', extra: 'pricing' },
  Chef: { k: 'people', role: 'Chef', title: 'Food that tastes like home, plated like art.', sub: 'Private dining, catering and cooking classes in Jaipur.', about: 'Trained at IHM and in kitchens from Mumbai to Paris. I cook seasonal Indian food with modern technique.', s: 'Indian cuisine, Fine dining, Menu design, Catering, Pastry', sv: [['Private dining', 'Chef’s table at your home.'], ['Catering', 'Events up to 300 guests.'], ['Classes', 'Hands-on cooking workshops.']], pr: [['Supper club', 'Monthly 12-seat dinners.', 'Dining'], ['Wedding feast', 'Menu for 300 guests.', 'Catering'], ['Cookbook', 'Recipes from Rajasthan.', 'Book']], ex: [['Chef-owner', 'Saffron Table', '2020 – now', 'Private dining.'], ['Sous Chef', 'The Oberoi', '2014 – 2020', 'Indian kitchen.']], st: [['12', 'Years cooking'], ['500+', 'Events catered'], ['1', 'Cookbook']], work: 'gallery', extra: 'pricing' },
  'Event Planner': { k: 'people', role: 'Event planner', title: 'Events people talk about for years.', sub: 'Weddings, corporate events and celebrations, fully managed.', about: 'Ten years planning weddings and events across Rajasthan. Every detail handled, so you can enjoy the day.', s: 'Wedding planning, Corporate events, Vendor management, Decor, Logistics', sv: [['Weddings', 'Destination and local weddings.'], ['Corporate', 'Offsites, launches, conferences.'], ['Celebrations', 'Birthdays and anniversaries.']], pr: [['Palace wedding', '600 guests in Udaipur.', 'Wedding'], ['Tech offsite', '300 people, 3 days.', 'Corporate'], ['Product launch', 'Launch event for a car brand.', 'Launch']], ex: [['Founder', 'Celebrate Co.', '2018 – now', 'Team of twelve.'], ['Event Manager', 'Wizcraft', '2014 – 2018', 'Large events.']], st: [['250+', 'Events planned'], ['10', 'Years experience'], ['30', 'Vendors on call']], work: 'gallery', extra: 'pricing' },
  Freelancer: { k: 'people', role: 'Freelancer', title: 'One person. Many skills. Zero fuss.', sub: 'Websites, design and content for small businesses and startups.', about: 'I have worked with 100+ clients across 12 countries. Clear quotes, quick replies, on-time delivery.', s: 'Web design, Branding, Copywriting, WordPress, Social media', sv: [['Websites', 'Fast, mobile-friendly sites.'], ['Branding', 'Logos and brand kits.'], ['Content', 'Copy, posts and blogs.']], pr: [['Bakery site', 'Online orders up 3×.', 'Web'], ['Startup brand', 'Logo and pitch deck.', 'Brand'], ['Content retainer', '12 months of blogs.', 'Content']], ex: [['Freelancer', 'Self-employed', '2019 – now', '100+ clients.'], ['Designer', 'Agency', '2016 – 2019', 'Web and brand.']], st: [['100+', 'Clients'], ['12', 'Countries'], ['5★', 'Upwork rating']], work: 'projects', extra: 'pricing' },
};

// ---------- composition ----------
const shortName = (n) => n.split(' ')[0];
const handle = (n) => n.toLowerCase().replace(/[^a-z]+/g, '.').replace(/\.$/, '');
const navLinks = (k) => (k === 'tech'
  ? [{ label: 'Projects', url: '#work' }, { label: 'Stack', url: '#skills' }, { label: 'Contact', url: '#contact' }]
  : [{ label: 'Work', url: '#work' }, { label: 'About', url: '#about' }, { label: 'Contact', url: '#contact' }]);

function heroBlock(p, L, name, seed) {
  const words = String(p.s).split(',').map((x) => x.trim());
  if (p.k === 'tech' && L.dev && (L.hero === 'feature' || L.hero === 'center')) {
    const extra = (p.stack || []).flatMap(([, items]) => items.split(',').map((x) => x.trim()));
    return b('hero3d', { kicker: `Hi, I’m ${shortName(name)} 👋`, title: p.title, subtitle: p.sub, available: 'Open to new projects', words: [...new Set([...words, ...extra])].join(', '), buttonText: 'See my work', button2Text: 'Get in touch' }, { paddingY: 100, anchor: 'home' });
  }
  const layout = L.hero === 'feature' ? 'center' : L.hero;
  const image = L.heroImage === false && layout === 'center' ? '' : img(`${seed}-hero`, layout === 'cover' ? 1800 : 800, layout === 'cover' ? 1100 : 1000);
  return b('hero', { layout, kicker: p.role, title: p.title, subtitle: p.sub, image, buttonText: p.k === 'people' ? 'Book a session' : 'See my work', button2Text: 'Contact me' },
    { paddingY: layout === 'center' ? 130 : undefined, width: layout === 'cover' ? 'full' : '', align: layout === 'center' ? 'center' : '' });
}

function sections(p, L, name, seed, cat) {
  const names = NAMES.filter((n) => n !== name);
  const out = {};
  out.about = b('about', { title: 'About', text: p.about, image: L.narrow ? '' : img(`${seed}-about`, 700, 800) }, { anchor: 'about', width: L.narrow ? 'narrow' : '' });
  out.stats = b('stats', { items: p.st.map(([value, label]) => ({ value, label })) }, { align: 'center' });
  out.services = b('services', { title: 'What I do', items: p.sv.map(([title, desc]) => ({ title, desc })) }, { anchor: 'services' });
  out.exp = b('experience', { title: 'Experience', items: p.ex.map(([role, company, period, desc]) => ({ role, company, period, desc })) }, { width: 'narrow' });
  out.testimonials = b('testimonials', { title: 'Kind words', items: QUOTES[p.k].map(([quote, role], i) => ({ quote, name: names[(i * 7 + seed.length) % names.length], role, avatar: img(`${seed}-av${i}`, 120, 120) })) });
  out.cta = b('cta', { title: p.k === 'people' ? 'Ready when you are' : 'Have a project in mind?', text: 'I usually reply within a day.', buttonText: 'Get in touch' });
  out.contact = b('contact', { title: 'Get in touch', text: 'Tell me a little about what you need.', email: `hello@${handle(name).replace(/\./g, '')}.com` }, { anchor: 'contact' });

  const skillItems = String(p.s).split(',').map((x, i) => ({ name: x.trim(), level: 95 - i * 6 }));
  if (p.k === 'tech' && L.skills !== 'circles') out.skills = b('techstack', { title: 'Tech stack', display: L.dev ? 'icons' : 'chips', groups: (p.stack || [['Skills', p.s]]).map(([gname, items]) => ({ name: gname, items })) }, { anchor: 'skills' });
  else out.skills = b('skills', { title: 'Skills', display: L.skills, items: skillItems }, { anchor: 'skills', align: L.skills === 'circles' ? 'center' : '' });

  const projItems = p.pr.map(([title, desc, tags], i) => ({ title, desc, tags, image: img(`${seed}-p${i}`, 900, 600), url: '#' }));
  if (p.k === 'tech' && L.dev) {
    out.work = b('featured', { title: 'Featured projects', layout: L.cols === 3 ? 'grid' : 'alternating', items: projItems.map((it) => ({ ...it, image: img(`${seed}-f${it.title.length}`, 1200, 800), metric: '', liveUrl: 'https://example.com', githubUrl: 'https://github.com', shots: [] })) }, { anchor: 'work' });
  } else if (p.work === 'gallery') {
    out.work = b('gallery', { title: 'Selected work', columns: L.gallery === 'wide' ? 2 : 3, layout: L.gallery, images: [0, 1, 2, 3, 4, 5].map((i) => ({ src: img(`${seed}-g${i}`, 900, L.gallery === 'masonry' && i % 2 ? 1150 : 800), caption: L.gallery === 'wide' ? p.pr[i % p.pr.length][0] : '' })) }, { anchor: 'work' });
  } else {
    out.work = b('projects', { title: p.k === 'business' ? 'Results' : 'Selected work', columns: L.cols, items: projItems }, { anchor: 'work' });
  }

  const extra = p.k === 'tech' ? (L.dev ? 'github' : p.extra || 'certs') : p.extra;
  if (extra === 'github') out.extra = b('github', { title: 'On GitHub' });
  else if (extra === 'certs') out.extra = b('certs', { title: 'Certifications', items: [{ name: `${cat} certification`, issuer: 'Industry body', date: '2025', url: '', badge: '', kind: 'Certification' }, { name: 'Top performer award', issuer: p.ex[0][1], date: '2024', url: '', badge: '', kind: 'Award' }] });
  else if (extra === 'logos') out.extra = b('logos', { title: 'Trusted by' });
  else if (extra === 'video') out.extra = b('video', { title: 'Showreel' });
  else if (extra === 'pricing') out.extra = b('pricing', { title: 'Packages', items: p.sv.map(([s], i) => ({ name: s, price: ['₹9,000', '₹25,000', 'On request'][i], features: ['Consultation', 'Clear timeline', 'Revisions included'].slice(0, 3 - (i === 2 ? 1 : 0)).join('\n'), highlight: i === 1 })) });
  else if (extra === 'faq') out.extra = b('faq', { title: 'Questions', items: [{ q: 'How do we start?', a: 'Send a short message with what you need and your timeline. I reply within a day.' }, { q: 'Do you work remotely?', a: 'Yes, with clients anywhere. In person in Jaipur too.' }, { q: 'How do you charge?', a: 'Fixed quotes for most work, agreed before we begin.' }] });
  else if (extra === 'map') out.extra = b('map', { query: 'MI Road, Jaipur' });
  else if (extra === 'education') out.extra = b('education', { title: 'Education', items: [{ degree: p.k === 'people' && cat === 'Student' ? 'B.Tech, Computer Science' : 'Postgraduate degree', school: 'University of Rajasthan', period: cat === 'Student' ? '2023 – 2027' : '2008 – 2010' }] });
  return out;
}

function linkBio(p, L, name, seed) {
  return [
    b('image', { src: img(`${seed}-avatar`, 300, 300), width: 30, rounded: true }, { paddingY: 48 }),
    b('heading', { text: '@' + handle(name), level: '2' }, { align: 'center', paddingY: 0 }),
    b('text', { text: p.sub }, { align: 'center', paddingY: 8 }),
    b('links', { items: p.links.map(([label, note]) => ({ label, url: 'https://example.com', note })) }, { paddingY: 24 }),
    b('video', { title: '' }, { paddingY: 24 }),
    b('social', { items: [{ platform: 'Instagram', url: 'https://instagram.com' }, { platform: 'YouTube', url: 'https://youtube.com' }, { platform: 'TikTok', url: 'https://tiktok.com' }] }, { align: 'center' }),
    b('footer', { text: `© 2026 ${name}` }),
  ];
}

function compose(p, L, name, seed, cat) {
  if (p.k === 'linkbio') return linkBio(p, L, name, seed);
  const s = sections(p, L, name, seed, cat);
  const middle = ORDERS[L.order].filter((k) => s[k]).map((k) => s[k]);
  if (L.band) middle.forEach((blk, i) => { if (i % 2 === 1 && !['stats', 'cta'].includes(blk.type)) blk.style = { ...blk.style, bg: L.theme.surface }; });
  const blocks = [b('navbar', { logo: L.slug === 'midnight' || L.slug === 'brutal' ? '~/' + handle(name).split('.')[0] : name, links: navLinks(p.k) }), heroBlock(p, L, name, seed), ...middle];
  if (p.k === 'tech' && L.dev) blocks.push(b('chatbot', { name: `${shortName(name)}’s assistant`, knowledge: [{ keywords: 'stack, tech, tools, skills', answer: `I work with ${p.s}.` }, { keywords: 'projects, work, built', answer: p.pr.map((x) => `${x[0]}: ${x[1]}`).join('\n') }, { keywords: 'hire, available, contact, email, freelance', answer: 'Yes, I’m open to new projects. Use the contact form below.' }] }));
  blocks.push(b('footer', { text: `© 2026 ${name}` }));
  return blocks;
}

const catSlug = (c) => c.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

// One template per style for every category, minus the hand-made ones already in that category.
export function generateTemplates(categories, existing) {
  const out = [];
  categories.forEach((cat, ci) => {
    const p = PACKS[cat];
    if (!p) return;
    const need = Math.max(0, 20 - existing.filter((t) => t.category === cat).length);
    for (let i = 0; i < need; i++) {
      const L = STYLES[(i + ci) % STYLES.length];
      const name = NAMES[(i * 3 + ci) % NAMES.length];
      const slug = `${catSlug(cat)}-${L.slug}`;
      const extra = p.k === 'tech' ? { commandPalette: true } : {};
      out.push({
        slug,
        name: `${L.name} ${p.k === 'linkbio' ? 'Links' : p.role.split(' ').slice(-1)[0].replace(/^\w/, (c) => c.toUpperCase())}`,
        category: cat,
        premium: L.premium,
        description: L.desc,
        theme: theme({ ...L.theme, modeToggle: !!L.mode, ...extra, ...(p.k === 'linkbio' ? { maxWidth: 640 } : {}) }),
        blocks: () => compose(p, L, name, slug, cat),
      });
    }
  });
  return out;
}

// ---------- curvy styles: curved edges and background shapes from lib/shapes.js ----------
// hero / band (every other middle section) / cta / footer are section-style patches
export const CURVY_STYLES = [
  { slug: 'lagoon', name: 'Lagoon', premium: false, desc: 'Layered waves and calm sea colours.', hero: 'split', order: 1, skills: 'bars', cols: 3, gallery: 'masonry',
    theme: { ...pal('#0F9BB5', '#FF8A5B', '#F3FBFC', '#FFFFFF', '#0B2A33', '#4F6B73', '#D3EAEE'), headingFont: 'Outfit', bodyFont: 'Inter', headingWeight: '700', radius: 20, buttonStyle: 'pill' },
    curves: {
      hero: { bg: '#CDEDF3', shapeBottom: 'layer-wave-3', shapeHeight: 110, decor: 'blob-4', decorPos: 'tr', decorSize: 420, decorOpacity: 18 },
      band: { bg: '#D6F0F5', shapeTop: 'wave-1_5', shapeBottom: 'wave-1_5', shapeHeight: 70 },
      cta: { tone: 'brand', shapeTop: 'ripple-4', shapeBottom: 'layer-ripple', shapeHeight: 60 },
      footer: { bg: '#CDEDF3', shapeTop: 'layer-wave-2', shapeHeight: 70 },
    } },
  { slug: 'bubblegum', name: 'Bubblegum', premium: false, desc: 'Clouds, scallops and floating flowers.', hero: 'split', order: 3, skills: 'circles', cols: 3, gallery: 'grid',
    theme: { ...pal('#E0457B', '#7C5CFF', '#FFF7FA', '#FFFFFF', '#2E1424', '#7A5B6B', '#F6DCE6'), headingFont: 'Fredoka', bodyFont: 'Nunito', headingWeight: '600', letterSpacing: -0.01, radius: 26, buttonStyle: 'pill' },
    curves: {
      hero: { bg: '#FFE3EE', shapeBottom: 'cloud-1', shapeHeight: 100, decor: 'flower', decorPos: 'both', decorSize: 300, decorOpacity: 20, decorMotion: true },
      band: { bg: '#FFE1EC', shapeTop: 'scallop-16', shapeBottom: 'scallop-16', shapeHeight: 40 },
      cta: { tone: 'brand', shapeBottom: 'drip-1', shapeHeight: 90 },
      footer: { bg: '#FFE3EE', shapeTop: 'cloud-3', shapeHeight: 70 },
    } },
  { slug: 'meadow', name: 'Meadow', premium: false, desc: 'Rolling green hills and organic edges.', hero: 'image-left', order: 0, skills: 'bars', cols: 3, gallery: 'grid',
    theme: { ...pal('#16A34A', '#FACC15', '#F6FDF7', '#FFFFFF', '#0E2A18', '#4F6B58', '#D6EFDD'), headingFont: 'Poppins', bodyFont: 'Figtree', headingWeight: '700', letterSpacing: -0.02, radius: 16 },
    curves: {
      hero: { bg: '#E3F7E8', shapeBottom: 'hills-layered', shapeHeight: 120, decor: 'blob-2', decorPos: 'tl', decorSize: 360, decorOpacity: 16 },
      band: { bg: '#DDF3E3', shapeTop: 'organic-3', shapeBottom: 'organic-5', shapeHeight: 70 },
      cta: { tone: 'brand', shapeTop: 'hills-2', shapeBottom: 'hills-3', shapeHeight: 70 },
      footer: { bg: '#E3F7E8', shapeTop: 'hills-far', shapeHeight: 80 },
    } },
  { slug: 'dune', name: 'Dune', premium: true, desc: 'Warm desert curves and a setting sun.', hero: 'split', order: 2, skills: 'tags', cols: 2, gallery: 'wide',
    theme: { ...pal('#C2410C', '#F4A261', '#FFF8F0', '#FFFFFF', '#2B1A10', '#7A6352', '#F1DFCC'), headingFont: 'Fraunces', bodyFont: 'DM Sans', headingWeight: '600', letterSpacing: -0.01, radius: 14 },
    curves: {
      hero: { bg: '#FCE7D4', shapeBottom: 'hills-far', shapeHeight: 130, decor: 'sun', decorPos: 'tr', decorSize: 260, decorOpacity: 40, decorColor: '#F4A261' },
      band: { bg: '#F8E3CF', shapeTop: 'swoosh-up', shapeBottom: 'swoosh-down', shapeHeight: 80 },
      cta: { tone: 'dark', shapeTop: 'hills-layered', shapeHeight: 90, decor: 'rainbow', decorPos: 'br', decorOpacity: 25, decorColor: '#F4A261' },
      footer: { bg: '#FCE7D4', shapeTop: 'swoosh-s', shapeHeight: 70 },
    } },
  { slug: 'petal', name: 'Petal', premium: true, desc: 'Soft lavender arcs with elegant serif type.', hero: 'center', heroImage: false, order: 1, skills: 'tags', cols: 3, gallery: 'masonry',
    theme: { ...pal('#7C3AED', '#F472B6', '#FBF9FF', '#FFFFFF', '#1F1633', '#6B6385', '#E8E1F7'), headingFont: 'Playfair Display', bodyFont: 'Jost', headingWeight: '700', letterSpacing: -0.01, radius: 18, buttonStyle: 'pill' },
    curves: {
      hero: { bg: '#F1EAFF', paddingY: 120, shapeBottom: 'curve-down-centre', shapeHeight: 120, decor: 'blob-7', decorPos: 'center', decorSize: 640, decorOpacity: 12 },
      band: { bg: '#ECE3FF', shapeTop: 'curve-flat-hill', shapeBottom: 'curve-flat-bowl', shapeHeight: 60 },
      cta: { tone: 'brand', shapeTop: 'curve-up-centre', shapeBottom: 'curve-down-centre', shapeHeight: 80, decor: 'rings', decorPos: 'tr', decorOpacity: 22 },
      footer: { bg: '#F1EAFF', shapeTop: 'arch-wide', shapeHeight: 60 },
    } },
  { slug: 'nightwave', name: 'Nightwave', premium: true, desc: 'Glowing waves on a deep violet night.', hero: 'split', order: 3, skills: 'tags', cols: 3, gallery: 'masonry',
    theme: { ...pal('#8B5CF6', '#22D3EE', '#0E0B1F', '#17132E', '#EDEAFF', '#9C96C0', '#2A2450'), headingFont: 'Space Grotesk', bodyFont: 'Inter', letterSpacing: -0.03, radius: 16, buttonStyle: 'pill', baseSize: 16 },
    curves: {
      hero: { bg: '#1A1440', shapeBottom: 'layer-wave-tri', shapeHeight: 110, decor: 'blob-9', decorPos: 'tr', decorSize: 520, decorOpacity: 30, decorMotion: true },
      band: { bg: '#1D1740', shapeTop: 'layer-cross', shapeBottom: 'layer-wave-2', shapeHeight: 80 },
      cta: { tone: 'brand', shapeTop: 'swoosh-ribbon', shapeBottom: 'swoosh-layer', shapeHeight: 80 },
      footer: { bg: '#1A1440', shapeTop: 'layer-wave-dbl', shapeHeight: 70 },
    } },
];

function curvify(blocks, L) {
  const c = L.curves;
  const add = (blk, patch) => { if (blk && patch) blk.style = { ...blk.style, ...patch }; };
  add(blocks.find((blk) => blk.type === 'hero'), c.hero);
  add(blocks.find((blk) => blk.type === 'footer'), c.footer);
  blocks.filter((blk) => blk.type === 'cta').forEach((blk) => add(blk, c.cta));
  const middle = blocks.filter((blk) => !['navbar', 'hero', 'footer', 'cta', 'chatbot'].includes(blk.type));
  middle.forEach((blk, i) => { if (i % 2 === 1 && blk.type !== 'stats') add(blk, c.band); });
  return blocks;
}

// Six curvy templates for every category (link-in-bio pages excluded)
export function generateCurvyTemplates(categories) {
  const out = [];
  categories.forEach((cat, ci) => {
    const p = PACKS[cat];
    if (!p || p.k === 'linkbio') return;
    CURVY_STYLES.forEach((L, i) => {
      const name = NAMES[(i * 5 + ci + 7) % NAMES.length];
      const slug = `${catSlug(cat)}-${L.slug}`;
      out.push({
        slug,
        name: `${L.name} ${p.role.split(' ').slice(-1)[0].replace(/^\w/, (ch) => ch.toUpperCase())}`,
        category: cat,
        premium: L.premium,
        description: L.desc,
        theme: theme({ ...L.theme, ...(p.k === 'tech' ? { commandPalette: true } : {}) }),
        blocks: () => curvify(compose(p, L, name, slug, cat), L),
      });
    });
  });
  return out;
}
